{"content": {"suites": {"0": {"status": {"total_pass": 4, "total_skip": 0, "total_xpass": 0, "total_xfail": 0, "total_rerun": 0, "total_fail": 3, "total_error": 0}, "tests": {"0": {"status": "PASS", "message": "", "test_name": "test_1_SetupOs", "rerun": "0"}, "1": {"status": "PASS", "message": "", "test_name": "test_2_Login", "rerun": "0"}, "2": {"status": "PASS", "message": "", "test_name": "test_3_AksesMenu", "rerun": "0"}, "3": {"status": "PASS", "message": "", "test_name": "test_4_ClickButtonTambah", "rerun": "0"}, "4": {"status": "FAIL", "message": "       NameError: name 'KegiatanKerjaFkr' is not defined\n       assert False\n", "test_name": "test_5_InputBidangGiatja", "rerun": "0"}, "5": {"status": "FAIL", "message": "           ConnectionRefusedError: [Errno 61] Connection refused\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x112314460>: Failed to establish a new connection: [Errno 61] Connection refused\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=61013): Max retries exceeded with url: /session/72ea9a02724817f9e4c555b8e861c5d4/timeouts (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x112314460>: Failed to establish a new connection: [Errno 61] Connection refused'))\n", "test_name": "test_20_tambahPeserta", "rerun": "0"}, "6": {"status": "FAIL", "message": "           ConnectionRefusedError: [Errno 61] Connection refused\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x115ce12b0>: Failed to establish a new connection: [Errno 61] Connection refused\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=61013): Max retries exceeded with url: /session/72ea9a02724817f9e4c555b8e861c5d4/window (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x115ce12b0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n", "test_name": "test_32_exit", "rerun": "0"}}, "suite_name": "1.KegiatanKerja/Fungsional/test_GiatjaTambah.py"}}}, "date": "May 03, 2023", "start_time": 1683090287.636957, "total_suite": 1, "status": "FAIL", "status_list": {"pass": "4", "fail": "3", "skip": "0", "error": "0", "xpass": "0", "xfail": "0", "rerun": "0"}, "total_tests": "7"}