{"content": {"suites": {"0": {"status": {"total_pass": 3, "total_skip": 0, "total_xpass": 0, "total_xfail": 0, "total_rerun": 0, "total_fail": 5, "total_error": 0}, "tests": {"0": {"status": "PASS", "message": "", "test_name": "test_1_SetupOs", "rerun": "0"}, "1": {"status": "PASS", "message": "", "test_name": "test_2_Login", "rerun": "0"}, "2": {"status": "PASS", "message": "", "test_name": "test_3_AksesMenu", "rerun": "0"}, "3": {"status": "FAIL", "message": "   selenium.common.exceptions.TimeoutException: Message: \n   Stacktrace:\n   0   chromedriver                        0x00000001050b6ae8 chromedriver + 4958952\n   1   chromedriver                        0x00000001050ae7b3 chromedriver + 4925363\n   2   chromedriver                        0x0000000104c701d6 chromedriver + 475606\n   3   chromedriver                        0x0000000104cb3a20 chromedriver + 752160\n   4   chromedriver                        0x0000000104cb3c81 chromedriver + 752769\n   5   chromedriver                        0x0000000104cf7f64 chromedriver + 1032036\n   6   chromedriver                        0x0000000104cd9c3d chromedriver + 908349\n   7   chromedriver                        0x0000000104cf525b chromedriver + 1020507\n   8   chromedriver                        0x0000000104cd99e3 chromedriver + 907747\n   9   chromedriver                        0x0000000104ca3aef chromedriver + 686831\n   10  chromedriver                        0x0000000104ca500e chromedriver + 692238\n   11  chromedriver                        0x00000001050729ad chromedriver + 4680109\n   12  chromedriver                        0x0000000105077c12 chromedriver + 4701202\n   13  chromedriver                        0x000000010507e79f chromedriver + 4728735\n   14  chromedriver                        0x0000000105078b7a chromedriver + 4705146\n   15  chromedriver                        0x000000010504b27e chromedriver + 4518526\n   16  chromedriver                        0x0000000105098908 chromedriver + 4835592\n   17  chromedriver                        0x0000000105098a87 chromedriver + 4835975\n   18  chromedriver                        0x00000001050a800f chromedriver + 4898831\n   19  libsystem_pthread.dylib             0x00007ff8161cb1d3 _pthread_start + 125\n   20  libsystem_pthread.dylib             0x00007ff8161c6bd3 thread_start + 15\n       assert False\n", "test_name": "test_4_ClickButtonTambah", "rerun": "0"}, "4": {"status": "FAIL", "message": "           ConnectionRefusedError: [Errno 61] Connection refused\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x11794be20>: Failed to establish a new connection: [Errno 61] Connection refused\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=58009): Max retries exceeded with url: /session/c17ae467f7aa441b486363cfb59cfc58/timeouts (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11794be20>: Failed to establish a new connection: [Errno 61] Connection refused'))\n", "test_name": "test_5_InputBidangGiatja", "rerun": "0"}, "5": {"status": "FAIL", "message": "           ConnectionRefusedError: [Errno 61] Connection refused\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x117db7520>: Failed to establish a new connection: [Errno 61] Connection refused\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=58009): Max retries exceeded with url: /session/c17ae467f7aa441b486363cfb59cfc58/timeouts (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x117db7520>: Failed to establish a new connection: [Errno 61] Connection refused'))\n", "test_name": "test_6_InputJenisKegiatanKerja", "rerun": "0"}, "6": {"status": "FAIL", "message": "           ConnectionRefusedError: [Errno 61] Connection refused\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x117be5100>: Failed to establish a new connection: [Errno 61] Connection refused\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=58009): Max retries exceeded with url: /session/c17ae467f7aa441b486363cfb59cfc58/timeouts (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x117be5100>: Failed to establish a new connection: [Errno 61] Connection refused'))\n", "test_name": "test_7_namaKegiatan", "rerun": "0"}, "7": {"status": "FAIL", "message": "           ConnectionRefusedError: [Errno 61] Connection refused\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x117d61250>: Failed to establish a new connection: [Errno 61] Connection refused\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=58009): Max retries exceeded with url: /session/c17ae467f7aa441b486363cfb59cfc58/window (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x117d61250>: Failed to establish a new connection: [Errno 61] Connection refused'))\n", "test_name": "test_32_exit", "rerun": "0"}}, "suite_name": "1.KegiatanKerja/Fungsional/test_GiatjaTambah.py"}}}, "date": "May 02, 2023", "start_time": 1683001024.695487, "total_suite": 1, "status": "FAIL", "status_list": {"pass": "3", "fail": "5", "skip": "0", "error": "0", "xpass": "0", "xfail": "0", "rerun": "0"}, "total_tests": "8"}