{"content": {"suites": {"0": {"status": {"total_pass": 6, "total_skip": 0, "total_xpass": 0, "total_xfail": 0, "total_rerun": 0, "total_fail": 8, "total_error": 0}, "tests": {"0": {"status": "PASS", "message": "", "test_name": "test_1_SetupOs", "rerun": "0"}, "1": {"status": "PASS", "message": "", "test_name": "test_2_Login", "rerun": "0"}, "2": {"status": "PASS", "message": "", "test_name": "test_2_AksesMenu", "rerun": "0"}, "3": {"status": "PASS", "message": "", "test_name": "test_3_CreateButton", "rerun": "0"}, "4": {"status": "PASS", "message": "", "test_name": "test_4_JenisGanggguan", "rerun": "0"}, "5": {"status": "PASS", "message": "", "test_name": "test_5_IdentitasPelaku", "rerun": "0"}, "6": {"status": "FAIL", "message": "           ConnectionRefusedError: [Errno 61] Connection refused\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x119fd3a00>: Failed to establish a new connection: [Errno 61] Connection refused\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=49860): Max retries exceeded with url: /session/c2cc4097a1187b1a7c5438906426f52b/timeouts (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x119fd3a00>: Failed to establish a new connection: [Errno 61] Connection refused'))\n", "test_name": "test_6_WaktuKejadian", "rerun": "0"}, "7": {"status": "FAIL", "message": "           ConnectionRefusedError: [Errno 61] Connection refused\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x11a3722b0>: Failed to establish a new connection: [Errno 61] Connection refused\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=49860): Max retries exceeded with url: /session/c2cc4097a1187b1a7c5438906426f52b/timeouts (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11a3722b0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n", "test_name": "test_7_TingkatGangguan", "rerun": "0"}, "8": {"status": "FAIL", "message": "           ConnectionRefusedError: [Errno 61] Connection refused\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x11a115370>: Failed to establish a new connection: [Errno 61] Connection refused\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=49860): Max retries exceeded with url: /session/c2cc4097a1187b1a7c5438906426f52b/timeouts (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11a115370>: Failed to establish a new connection: [Errno 61] Connection refused'))\n", "test_name": "test_8_Korban", "rerun": "0"}, "9": {"status": "FAIL", "message": "           ConnectionRefusedError: [Errno 61] Connection refused\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x11a4b8130>: Failed to establish a new connection: [Errno 61] Connection refused\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=49860): Max retries exceeded with url: /session/c2cc4097a1187b1a7c5438906426f52b/timeouts (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11a4b8130>: Failed to establish a new connection: [Errno 61] Connection refused'))\n", "test_name": "test_9_Kerugian", "rerun": "0"}, "10": {"status": "FAIL", "message": "           ConnectionRefusedError: [Errno 61] Connection refused\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x11a48d310>: Failed to establish a new connection: [Errno 61] Connection refused\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=49860): Max retries exceeded with url: /session/c2cc4097a1187b1a7c5438906426f52b/timeouts (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11a48d310>: Failed to establish a new connection: [Errno 61] Connection refused'))\n", "test_name": "test_10_TindakLanjut", "rerun": "0"}, "11": {"status": "FAIL", "message": "           ConnectionRefusedError: [Errno 61] Connection refused\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x11a318190>: Failed to establish a new connection: [Errno 61] Connection refused\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=49860): Max retries exceeded with url: /session/c2cc4097a1187b1a7c5438906426f52b/timeouts (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11a318190>: Failed to establish a new connection: [Errno 61] Connection refused'))\n", "test_name": "test_11_Keterangan", "rerun": "0"}, "12": {"status": "FAIL", "message": "           ConnectionRefusedError: [Errno 61] Connection refused\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x11a442070>: Failed to establish a new connection: [Errno 61] Connection refused\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=49860): Max retries exceeded with url: /session/c2cc4097a1187b1a7c5438906426f52b/timeouts (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11a442070>: Failed to establish a new connection: [Errno 61] Connection refused'))\n", "test_name": "test_12_SubmitButton", "rerun": "0"}, "13": {"status": "FAIL", "message": "           ConnectionRefusedError: [Errno 61] Connection refused\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x11a27ed60>: Failed to establish a new connection: [Errno 61] Connection refused\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=49860): Max retries exceeded with url: /session/c2cc4097a1187b1a7c5438906426f52b/window (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11a27ed60>: Failed to establish a new connection: [Errno 61] Connection refused'))\n", "test_name": "test_29_exit", "rerun": "0"}}, "suite_name": "4LaporanBulanan/9.Laporan7C/Fungsional/test_Laporan7C.py"}}}, "date": "April 17, 2023", "start_time": 1681713456.6046872, "total_suite": 1, "status": "FAIL", "status_list": {"pass": "6", "fail": "8", "skip": "0", "error": "0", "xpass": "0", "xfail": "0", "rerun": "0"}, "total_tests": "14"}