{"content": {"suites": {"0": {"status": {"total_pass": 2, "total_skip": 0, "total_xpass": 0, "total_xfail": 0, "total_rerun": 0, "total_fail": 1, "total_error": 0}, "tests": {"0": {"status": "PASS", "message": "", "test_name": "test_1_setupOS", "rerun": "0"}, "1": {"status": "PASS", "message": "", "test_name": "test_2_login", "rerun": "0"}, "2": {"status": "FAIL", "message": "           ConnectionRefusedError: [Errno 61] Connection refused\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x10c77ed30>: Failed to establish a new connection: [Errno 61] Connection refused\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=65286): Max retries exceeded with url: /session/28cdd9c770e469c3a4babacbd865b366/timeouts (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10c77ed30>: Failed to establish a new connection: [Errno 61] Connection refused'))\n", "test_name": "test_3_Input", "rerun": "0"}}, "suite_name": "test_AksesP2UInternal_Tambah.py"}}}, "date": "March 06, 2023", "start_time": 1678078633.727617, "total_suite": 1, "status": "FAIL", "status_list": {"pass": "2", "fail": "1", "skip": "0", "error": "0", "xpass": "0", "xfail": "0", "rerun": "0"}, "total_tests": "3"}