{"content": {"suites": {"0": {"status": {"total_pass": 4, "total_skip": 0, "total_xpass": 0, "total_xfail": 0, "total_rerun": 0, "total_fail": 3, "total_error": 0}, "tests": {"0": {"status": "PASS", "message": "", "test_name": "test_1_SetupOs", "rerun": "0"}, "1": {"status": "PASS", "message": "", "test_name": "test_2_Login", "rerun": "0"}, "2": {"status": "PASS", "message": "", "test_name": "test_2_AksesMenu", "rerun": "0"}, "3": {"status": "PASS", "message": "", "test_name": "test_3_CreateButton", "rerun": "0"}, "4": {"status": "FAIL", "message": "       NameError: name 'nosrtfkr' is not defined\n       assert False\n", "test_name": "test_4_InpuNoSuratPerintah", "rerun": "0"}, "5": {"status": "FAIL", "message": "           ConnectionRefusedError: [Errno 61] Connection refused\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x10fded370>: Failed to establish a new connection: [Errno 61] Connection refused\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=54813): Max retries exceeded with url: /session/1f23cadd9c9abdfa3f17a8534ea6ba6d/timeouts (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10fded370>: Failed to establish a new connection: [Errno 61] Connection refused'))\n", "test_name": "test_5_InputTanggalPelaksanaan", "rerun": "0"}, "6": {"status": "FAIL", "message": "           ConnectionRefusedError: [Errno 61] Connection refused\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x12a233310>: Failed to establish a new connection: [Errno 61] Connection refused\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=54813): Max retries exceeded with url: /session/1f23cadd9c9abdfa3f17a8534ea6ba6d/window (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x12a233310>: Failed to establish a new connection: [Errno 61] Connection refused'))\n", "test_name": "test_37_exit", "rerun": "0"}}, "suite_name": "4LaporanBulanan/5.Laporan6E copy/Fungsional/test_Laporan7A.py"}}}, "date": "April 12, 2023", "start_time": 1681282721.5205052, "total_suite": 1, "status": "FAIL", "status_list": {"pass": "4", "fail": "3", "skip": "0", "error": "0", "xpass": "0", "xfail": "0", "rerun": "0"}, "total_tests": "7"}