{"content": {"suites": {"0": {"status": {"total_pass": 2, "total_skip": 0, "total_xpass": 0, "total_xfail": 0, "total_rerun": 0, "total_fail": 2, "total_error": 0}, "tests": {"0": {"status": "PASS", "message": "", "test_name": "test_1_setupOS", "rerun": "0"}, "1": {"status": "PASS", "message": "", "test_name": "test_2_login", "rerun": "0"}, "2": {"status": "FAIL", "message": "           ConnectionRefusedError: [Errno 61] Connection refused\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x1123acca0>: Failed to establish a new connection: [Errno 61] Connection refused\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=62953): Max retries exceeded with url: /session/fb224557c62d3a85877add9bf33d6dcf/timeouts (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1123acca0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n", "test_name": "test_Input_Registrasi", "rerun": "0"}, "3": {"status": "FAIL", "message": "           ConnectionRefusedError: [Errno 61] Connection refused\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x116d1b700>: Failed to establish a new connection: [Errno 61] Connection refused\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=62953): Max retries exceeded with url: /session/fb224557c62d3a85877add9bf33d6dcf/window (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x116d1b700>: Failed to establish a new connection: [Errno 61] Connection refused'))\n", "test_name": "test_exit", "rerun": "0"}}, "suite_name": "test_registrasi.py"}}}, "date": "March 21, 2023", "start_time": 1679387194.685056, "total_suite": 1, "status": "FAIL", "status_list": {"pass": "2", "fail": "2", "skip": "0", "error": "0", "xpass": "0", "xfail": "0", "rerun": "0"}, "total_tests": "4"}