{"content": {"suites": {"0": {"status": {"total_pass": 2, "total_skip": 0, "total_xpass": 0, "total_xfail": 0, "total_rerun": 0, "total_fail": 2, "total_error": 0}, "tests": {"0": {"status": "PASS", "message": "", "test_name": "test_1_setupOS", "rerun": "0"}, "1": {"status": "PASS", "message": "", "test_name": "test_2_login", "rerun": "0"}, "2": {"status": "FAIL", "message": "           ConnectionRefusedError: [Errno 61] Connection refused\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x1178d68b0>: Failed to establish a new connection: [Errno 61] Connection refused\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=62969): Max retries exceeded with url: /session/52dddbcd4edc151412fae45717f97c2d/timeouts (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1178d68b0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n", "test_name": "test_Input", "rerun": "0"}, "3": {"status": "FAIL", "message": "           ConnectionRefusedError: [Errno 61] Connection refused\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x117b6d3a0>: Failed to establish a new connection: [Errno 61] Connection refused\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=62969): Max retries exceeded with url: /session/52dddbcd4edc151412fae45717f97c2d/window (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x117b6d3a0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n", "test_name": "test_exit", "rerun": "0"}}, "suite_name": "test_Petugas.py"}, "1": {"suite_name": "test_registrasi.py", "tests": {"0": {"status": "PASS", "message": "", "test_name": "test_1_setupOS", "rerun": "0"}, "1": {"status": "PASS", "message": "", "test_name": "test_2_login", "rerun": "0"}}, "status": {"total_pass": 2, "total_skip": 0, "total_xpass": 0, "total_xfail": 0, "total_rerun": 0, "total_fail": 0, "total_error": 0}}}}, "date": "January 27, 2023", "start_time": 1674804668.56548, "total_suite": 2, "status": "FAIL", "status_list": {"pass": "4", "fail": "2", "skip": "0", "error": "0", "xpass": "0", "xfail": "0", "rerun": "0"}, "total_tests": "6"}