{"content": {"suites": {"0": {"status": {"total_pass": 5, "total_skip": 0, "total_xpass": 0, "total_xfail": 0, "total_rerun": 0, "total_fail": 26, "total_error": 0}, "tests": {"0": {"status": "PASS", "message": "", "test_name": "test_1_SetupOs", "rerun": "0"}, "1": {"status": "PASS", "message": "", "test_name": "test_2_Login", "rerun": "0"}, "2": {"status": "FAIL", "message": "   selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {\"method\":\"css selector\",\"selector\":\"[id=\"KEA00\"]\"}\n     (Session info: chrome=112.0.5615.137)\n   Stacktrace:\n   0   chromedriver                        0x0000000100d9cae8 chromedriver + 4958952\n   1   chromedriver                        0x0000000100d947b3 chromedriver + 4925363\n   2   chromedriver                        0x00000001009561d6 chromedriver + 475606\n   3   chromedriver                        0x0000000100999a20 chromedriver + 752160\n   4   chromedriver                        0x0000000100999c81 chromedriver + 752769\n   5   chromedriver                        0x00000001009ddf64 chromedriver + 1032036\n   6   chromedriver                        0x00000001009bfc3d chromedriver + 908349\n   7   chromedriver                        0x00000001009db25b chromedriver + 1020507\n   8   chromedriver                        0x00000001009bf9e3 chromedriver + 907747\n   9   chromedriver                        0x0000000100989aef chromedriver + 686831\n   10  chromedriver                        0x000000010098b00e chromedriver + 692238\n   11  chromedriver                        0x0000000100d589ad chromedriver + 4680109\n   12  chromedriver                        0x0000000100d5dc12 chromedriver + 4701202\n   13  chromedriver                        0x0000000100d6479f chromedriver + 4728735\n   14  chromedriver                        0x0000000100d5eb7a chromedriver + 4705146\n   15  chromedriver                        0x0000000100d3127e chromedriver + 4518526\n   16  chromedriver                        0x0000000100d7e908 chromedriver + 4835592\n   17  chromedriver                        0x0000000100d7ea87 chromedriver + 4835975\n   18  chromedriver                        0x0000000100d8e00f chromedriver + 4898831\n   19  libsystem_pthread.dylib             0x00007ff80f4a71d3 _pthread_start + 125\n   20  libsystem_pthread.dylib             0x00007ff80f4a2bd3 thread_start + 15\n", "test_name": "test_3_AksesMenu", "rerun": "0"}, "3": {"status": "FAIL", "message": "   selenium.common.exceptions.TimeoutException: Message: \n   Stacktrace:\n   0   chromedriver                        0x0000000100d9cae8 chromedriver + 4958952\n   1   chromedriver                        0x0000000100d947b3 chromedriver + 4925363\n   2   chromedriver                        0x00000001009561d6 chromedriver + 475606\n   3   chromedriver                        0x0000000100999a20 chromedriver + 752160\n   4   chromedriver                        0x0000000100999c81 chromedriver + 752769\n   5   chromedriver                        0x00000001009ddf64 chromedriver + 1032036\n   6   chromedriver                        0x00000001009bfc3d chromedriver + 908349\n   7   chromedriver                        0x00000001009db25b chromedriver + 1020507\n   8   chromedriver                        0x00000001009bf9e3 chromedriver + 907747\n   9   chromedriver                        0x0000000100989aef chromedriver + 686831\n   10  chromedriver                        0x000000010098b00e chromedriver + 692238\n   11  chromedriver                        0x0000000100d589ad chromedriver + 4680109\n   12  chromedriver                        0x0000000100d5dc12 chromedriver + 4701202\n   13  chromedriver                        0x0000000100d6479f chromedriver + 4728735\n   14  chromedriver                        0x0000000100d5eb7a chromedriver + 4705146\n   15  chromedriver                        0x0000000100d3127e chromedriver + 4518526\n   16  chromedriver                        0x0000000100d7e908 chromedriver + 4835592\n   17  chromedriver                        0x0000000100d7ea87 chromedriver + 4835975\n   18  chromedriver                        0x0000000100d8e00f chromedriver + 4898831\n   19  libsystem_pthread.dylib             0x00007ff80f4a71d3 _pthread_start + 125\n   20  libsystem_pthread.dylib             0x00007ff80f4a2bd3 thread_start + 15\n       assert False\n", "test_name": "test_4_ClickButtonTambah", "rerun": "0"}, "4": {"status": "FAIL", "message": "           ConnectionRefusedError: [Errno 61] Connection refused\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x1158032b0>: Failed to establish a new connection: [Errno 61] Connection refused\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=53748): Max retries exceeded with url: /session/9001602799c1554a575be98b6f226383/timeouts (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1158032b0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n", "test_name": "test_5_penanggungJawab", "rerun": "0"}, "5": {"status": "FAIL", "message": "           ConnectionRefusedError: [Errno 61] Connection refused\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x115b720d0>: Failed to establish a new connection: [Errno 61] Connection refused\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=53748): Max retries exceeded with url: /session/9001602799c1554a575be98b6f226383/timeouts (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x115b720d0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n", "test_name": "test_6_jumlahAnggota", "rerun": "0"}, "6": {"status": "FAIL", "message": "           ConnectionRefusedError: [Errno 61] Connection refused\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x1159889a0>: Failed to establish a new connection: [Errno 61] Connection refused\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=53748): Max retries exceeded with url: /session/9001602799c1554a575be98b6f226383/timeouts (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1159889a0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n", "test_name": "test_7_pembagianTugas", "rerun": "0"}, "7": {"status": "FAIL", "message": "           ConnectionRefusedError: [Errno 61] Connection refused\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x115b38fd0>: Failed to establish a new connection: [Errno 61] Connection refused\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=53748): Max retries exceeded with url: /session/9001602799c1554a575be98b6f226383/timeouts (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x115b38fd0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n", "test_name": "test_11_keterangan", "rerun": "0"}, "8": {"status": "FAIL", "message": "           ConnectionRefusedError: [Errno 61] Connection refused\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x11586f100>: Failed to establish a new connection: [Errno 61] Connection refused\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=53748): Max retries exceeded with url: /session/9001602799c1554a575be98b6f226383/timeouts (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11586f100>: Failed to establish a new connection: [Errno 61] Connection refused'))\n", "test_name": "test_9_permasalahan", "rerun": "0"}, "9": {"status": "FAIL", "message": "           ConnectionRefusedError: [Errno 61] Connection refused\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x115b68160>: Failed to establish a new connection: [Errno 61] Connection refused\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=53748): Max retries exceeded with url: /session/9001602799c1554a575be98b6f226383/timeouts (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x115b68160>: Failed to establish a new connection: [Errno 61] Connection refused'))\n", "test_name": "test_8_rekapitulasiKehadiran", "rerun": "0"}, "10": {"status": "FAIL", "message": "           ConnectionRefusedError: [Errno 61] Connection refused\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x115925190>: Failed to establish a new connection: [Errno 61] Connection refused\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=53748): Max retries exceeded with url: /session/9001602799c1554a575be98b6f226383/timeouts (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x115925190>: Failed to establish a new connection: [Errno 61] Connection refused'))\n", "test_name": "test_10_alternatifPenyelesaian", "rerun": "0"}, "11": {"status": "FAIL", "message": "           ConnectionRefusedError: [Errno 61] Connection refused\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x115b9a220>: Failed to establish a new connection: [Errno 61] Connection refused\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=53748): Max retries exceeded with url: /session/9001602799c1554a575be98b6f226383/timeouts (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x115b9a220>: Failed to establish a new connection: [Errno 61] Connection refused'))\n", "test_name": "test_12_simpan", "rerun": "0"}, "12": {"status": "PASS", "message": "", "test_name": "test_13_SetupOs", "rerun": "0"}, "13": {"status": "FAIL", "message": "   selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed\n   from unknown error: web view not found\n     (Session info: chrome=112.0.5615.137)\n   Stacktrace:\n   0   chromedriver                        0x0000000102f40ae8 chromedriver + 4958952\n   1   chromedriver                        0x0000000102f387b3 chromedriver + 4925363\n   2   chromedriver                        0x0000000102afa1d6 chromedriver + 475606\n   3   chromedriver                        0x0000000102acfcec chromedriver + 302316\n   4   chromedriver                        0x0000000102b68f2f chromedriver + 929583\n   5   chromedriver                        0x0000000102b7e926 chromedriver + 1018150\n   6   chromedriver                        0x0000000102b639e3 chromedriver + 907747\n   7   chromedriver                        0x0000000102b2daef chromedriver + 686831\n   8   chromedriver                        0x0000000102b2f00e chromedriver + 692238\n   9   chromedriver                        0x0000000102efc9ad chromedriver + 4680109\n   10  chromedriver                        0x0000000102f01c12 chromedriver + 4701202\n   11  chromedriver                        0x0000000102f0879f chromedriver + 4728735\n   12  chromedriver                        0x0000000102f02b7a chromedriver + 4705146\n   13  chromedriver                        0x0000000102ed527e chromedriver + 4518526\n   14  chromedriver                        0x0000000102f22908 chromedriver + 4835592\n   15  chromedriver                        0x0000000102f22a87 chromedriver + 4835975\n   16  chromedriver                        0x0000000102f3200f chromedriver + 4898831\n   17  libsystem_pthread.dylib             0x00007ff80f4a71d3 _pthread_start + 125\n   18  libsystem_pthread.dylib             0x00007ff80f4a2bd3 thread_start + 15\n", "test_name": "test_14_LoginSPV", "rerun": "0"}, "14": {"status": "FAIL", "message": "   selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed\n   from unknown error: web view not found\n     (Session info: chrome=112.0.5615.137)\n   Stacktrace:\n   0   chromedriver                        0x0000000102f40ae8 chromedriver + 4958952\n   1   chromedriver                        0x0000000102f387b3 chromedriver + 4925363\n   2   chromedriver                        0x0000000102afa1d6 chromedriver + 475606\n   3   chromedriver                        0x0000000102acfcec chromedriver + 302316\n   4   chromedriver                        0x0000000102b68f2f chromedriver + 929583\n   5   chromedriver                        0x0000000102b7e926 chromedriver + 1018150\n   6   chromedriver                        0x0000000102b639e3 chromedriver + 907747\n   7   chromedriver                        0x0000000102b2daef chromedriver + 686831\n   8   chromedriver                        0x0000000102b2f00e chromedriver + 692238\n   9   chromedriver                        0x0000000102efc9ad chromedriver + 4680109\n   10  chromedriver                        0x0000000102f01c12 chromedriver + 4701202\n   11  chromedriver                        0x0000000102f0879f chromedriver + 4728735\n   12  chromedriver                        0x0000000102f02b7a chromedriver + 4705146\n   13  chromedriver                        0x0000000102ed527e chromedriver + 4518526\n   14  chromedriver                        0x0000000102f22908 chromedriver + 4835592\n   15  chromedriver                        0x0000000102f22a87 chromedriver + 4835975\n   16  chromedriver                        0x0000000102f3200f chromedriver + 4898831\n   17  libsystem_pthread.dylib             0x00007ff80f4a71d3 _pthread_start + 125\n   18  libsystem_pthread.dylib             0x00007ff80f4a2bd3 thread_start + 15\n   selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed\n   from unknown error: web view not found\n     (Session info: chrome=112.0.5615.137)\n   Stacktrace:\n   0   chromedriver                        0x0000000102f40ae8 chromedriver + 4958952\n   1   chromedriver                        0x0000000102f387b3 chromedriver + 4925363\n   2   chromedriver                        0x0000000102afa1d6 chromedriver + 475606\n   3   chromedriver                        0x0000000102acfcec chromedriver + 302316\n   4   chromedriver                        0x0000000102b68f2f chromedriver + 929583\n   5   chromedriver                        0x0000000102b6fc7c chromedriver + 957564\n   6   chromedriver                        0x0000000102b63bd8 chromedriver + 908248\n   7   chromedriver                        0x0000000102b2daef chromedriver + 686831\n   8   chromedriver                        0x0000000102b2f00e chromedriver + 692238\n   9   chromedriver                        0x0000000102efc9ad chromedriver + 4680109\n   10  chromedriver                        0x0000000102f01c12 chromedriver + 4701202\n   11  chromedriver                        0x0000000102f0879f chromedriver + 4728735\n   12  chromedriver                        0x0000000102f02b7a chromedriver + 4705146\n   13  chromedriver                        0x0000000102ed527e chromedriver + 4518526\n   14  chromedriver                        0x0000000102f22908 chromedriver + 4835592\n   15  chromedriver                        0x0000000102f22a87 chromedriver + 4835975\n   16  chromedriver                        0x0000000102f3200f chromedriver + 4898831\n   17  libsystem_pthread.dylib             0x00007ff80f4a71d3 _pthread_start + 125\n   18  libsystem_pthread.dylib             0x00007ff80f4a2bd3 thread_start + 15\n", "test_name": "test_15_AksesMenuSpv", "rerun": "0"}, "15": {"status": "FAIL", "message": "   selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed\n   from unknown error: web view not found\n     (Session info: chrome=112.0.5615.137)\n   Stacktrace:\n   0   chromedriver                        0x0000000102f40ae8 chromedriver + 4958952\n   1   chromedriver                        0x0000000102f387b3 chromedriver + 4925363\n   2   chromedriver                        0x0000000102afa1d6 chromedriver + 475606\n   3   chromedriver                        0x0000000102acfcec chromedriver + 302316\n   4   chromedriver                        0x0000000102b68f2f chromedriver + 929583\n   5   chromedriver                        0x0000000102b7e926 chromedriver + 1018150\n   6   chromedriver                        0x0000000102b639e3 chromedriver + 907747\n   7   chromedriver                        0x0000000102b2daef chromedriver + 686831\n   8   chromedriver                        0x0000000102b2f00e chromedriver + 692238\n   9   chromedriver                        0x0000000102efc9ad chromedriver + 4680109\n   10  chromedriver                        0x0000000102f01c12 chromedriver + 4701202\n   11  chromedriver                        0x0000000102f0879f chromedriver + 4728735\n   12  chromedriver                        0x0000000102f02b7a chromedriver + 4705146\n   13  chromedriver                        0x0000000102ed527e chromedriver + 4518526\n   14  chromedriver                        0x0000000102f22908 chromedriver + 4835592\n   15  chromedriver                        0x0000000102f22a87 chromedriver + 4835975\n   16  chromedriver                        0x0000000102f3200f chromedriver + 4898831\n   17  libsystem_pthread.dylib             0x00007ff80f4a71d3 _pthread_start + 125\n   18  libsystem_pthread.dylib             0x00007ff80f4a2bd3 thread_start + 15\n   selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed\n   from unknown error: web view not found\n     (Session info: chrome=112.0.5615.137)\n   Stacktrace:\n   0   chromedriver                        0x0000000102f40ae8 chromedriver + 4958952\n   1   chromedriver                        0x0000000102f387b3 chromedriver + 4925363\n   2   chromedriver                        0x0000000102afa1d6 chromedriver + 475606\n   3   chromedriver                        0x0000000102acfcec chromedriver + 302316\n   4   chromedriver                        0x0000000102b68f2f chromedriver + 929583\n   5   chromedriver                        0x0000000102b7e926 chromedriver + 1018150\n   6   chromedriver                        0x0000000102b639e3 chromedriver + 907747\n   7   chromedriver                        0x0000000102b2daef chromedriver + 686831\n   8   chromedriver                        0x0000000102b2f00e chromedriver + 692238\n   9   chromedriver                        0x0000000102efc9ad chromedriver + 4680109\n   10  chromedriver                        0x0000000102f01c12 chromedriver + 4701202\n   11  chromedriver                        0x0000000102f0879f chromedriver + 4728735\n   12  chromedriver                        0x0000000102f02b7a chromedriver + 4705146\n   13  chromedriver                        0x0000000102ed527e chromedriver + 4518526\n   14  chromedriver                        0x0000000102f22908 chromedriver + 4835592\n   15  chromedriver                        0x0000000102f22a87 chromedriver + 4835975\n   16  chromedriver                        0x0000000102f3200f chromedriver + 4898831\n   17  libsystem_pthread.dylib             0x00007ff80f4a71d3 _pthread_start + 125\n   18  libsystem_pthread.dylib             0x00007ff80f4a2bd3 thread_start + 15\n", "test_name": "test_16_KirimLaporanSpv", "rerun": "0"}, "16": {"status": "PASS", "message": "", "test_name": "test_17_loginKanwil", "rerun": "0"}, "17": {"status": "FAIL", "message": "   selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {\"method\":\"css selector\",\"selector\":\"[id=\"KEA00\"]\"}\n     (Session info: chrome=112.0.5615.137)\n   Stacktrace:\n   0   chromedriver                        0x0000000102f2cae8 chromedriver + 4958952\n   1   chromedriver                        0x0000000102f247b3 chromedriver + 4925363\n   2   chromedriver                        0x0000000102ae61d6 chromedriver + 475606\n   3   chromedriver                        0x0000000102b29a20 chromedriver + 752160\n   4   chromedriver                        0x0000000102b29c81 chromedriver + 752769\n   5   chromedriver                        0x0000000102b6df64 chromedriver + 1032036\n   6   chromedriver                        0x0000000102b4fc3d chromedriver + 908349\n   7   chromedriver                        0x0000000102b6b25b chromedriver + 1020507\n   8   chromedriver                        0x0000000102b4f9e3 chromedriver + 907747\n   9   chromedriver                        0x0000000102b19aef chromedriver + 686831\n   10  chromedriver                        0x0000000102b1b00e chromedriver + 692238\n   11  chromedriver                        0x0000000102ee89ad chromedriver + 4680109\n   12  chromedriver                        0x0000000102eedc12 chromedriver + 4701202\n   13  chromedriver                        0x0000000102ef479f chromedriver + 4728735\n   14  chromedriver                        0x0000000102eeeb7a chromedriver + 4705146\n   15  chromedriver                        0x0000000102ec127e chromedriver + 4518526\n   16  chromedriver                        0x0000000102f0e908 chromedriver + 4835592\n   17  chromedriver                        0x0000000102f0ea87 chromedriver + 4835975\n   18  chromedriver                        0x0000000102f1e00f chromedriver + 4898831\n   19  libsystem_pthread.dylib             0x00007ff80f4a71d3 _pthread_start + 125\n   20  libsystem_pthread.dylib             0x00007ff80f4a2bd3 thread_start + 15\n       assert False\n", "test_name": "test_18_AksesMenuKanwil", "rerun": "0"}, "18": {"status": "FAIL", "message": "           ConnectionRefusedError: [Errno 61] Connection refused\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x115803880>: Failed to establish a new connection: [Errno 61] Connection refused\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=54332): Max retries exceeded with url: /session/b87f49bd51b9532a3fede141449ed978/timeouts (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x115803880>: Failed to establish a new connection: [Errno 61] Connection refused'))\n           ConnectionRefusedError: [Errno 61] Connection refused\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x1158035e0>: Failed to establish a new connection: [Errno 61] Connection refused\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=54332): Max retries exceeded with url: /session/b87f49bd51b9532a3fede141449ed978/screenshot (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1158035e0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n", "test_name": "test_19_VerifikasiLaporanKanwil", "rerun": "0"}, "19": {"status": "FAIL", "message": "           ConnectionRefusedError: [Errno 61] Connection refused\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x115b70310>: Failed to establish a new connection: [Errno 61] Connection refused\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=54332): Max retries exceeded with url: /session/b87f49bd51b9532a3fede141449ed978/timeouts (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x115b70310>: Failed to establish a new connection: [Errno 61] Connection refused'))\n", "test_name": "test_20_ClickButtonSearch", "rerun": "0"}, "20": {"status": "FAIL", "message": "           ConnectionRefusedError: [Errno 61] Connection refused\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x115967be0>: Failed to establish a new connection: [Errno 61] Connection refused\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=54332): Max retries exceeded with url: /session/b87f49bd51b9532a3fede141449ed978/timeouts (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x115967be0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n", "test_name": "test_21_ClickButtonVerifikasi", "rerun": "0"}, "21": {"status": "FAIL", "message": "           ConnectionRefusedError: [Errno 61] Connection refused\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x115c3eac0>: Failed to establish a new connection: [Errno 61] Connection refused\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=54332): Max retries exceeded with url: /session/b87f49bd51b9532a3fede141449ed978/timeouts (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x115c3eac0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n", "test_name": "test_22_StatusVerifikasiModal", "rerun": "0"}, "22": {"status": "FAIL", "message": "           ConnectionRefusedError: [Errno 61] Connection refused\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x115792fd0>: Failed to establish a new connection: [Errno 61] Connection refused\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=54332): Max retries exceeded with url: /session/b87f49bd51b9532a3fede141449ed978/timeouts (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x115792fd0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n", "test_name": "test_23_UbahStatus", "rerun": "0"}, "23": {"status": "FAIL", "message": "           ConnectionRefusedError: [Errno 61] Connection refused\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x115a4e3d0>: Failed to establish a new connection: [Errno 61] Connection refused\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=54332): Max retries exceeded with url: /session/b87f49bd51b9532a3fede141449ed978/timeouts (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x115a4e3d0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n", "test_name": "test_24_Inputketerangan", "rerun": "0"}, "24": {"status": "FAIL", "message": "           ConnectionRefusedError: [Errno 61] Connection refused\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x115bf5370>: Failed to establish a new connection: [Errno 61] Connection refused\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=54332): Max retries exceeded with url: /session/b87f49bd51b9532a3fede141449ed978/timeouts (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x115bf5370>: Failed to establish a new connection: [Errno 61] Connection refused'))\n", "test_name": "test_25_SimpanVerifikasi", "rerun": "0"}, "25": {"status": "PASS", "message": "", "test_name": "test_26_loginPusat", "rerun": "0"}, "26": {"status": "FAIL", "message": "   selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {\"method\":\"css selector\",\"selector\":\"[id=\"KEA00\"]\"}\n     (Session info: chrome=112.0.5615.137)\n   Stacktrace:\n   0   chromedriver                        0x00000001052beae8 chromedriver + 4958952\n   1   chromedriver                        0x00000001052b67b3 chromedriver + 4925363\n   2   chromedriver                        0x0000000104e781d6 chromedriver + 475606\n   3   chromedriver                        0x0000000104ebba20 chromedriver + 752160\n   4   chromedriver                        0x0000000104ebbc81 chromedriver + 752769\n   5   chromedriver                        0x0000000104efff64 chromedriver + 1032036\n   6   chromedriver                        0x0000000104ee1c3d chromedriver + 908349\n   7   chromedriver                        0x0000000104efd25b chromedriver + 1020507\n   8   chromedriver                        0x0000000104ee19e3 chromedriver + 907747\n   9   chromedriver                        0x0000000104eabaef chromedriver + 686831\n   10  chromedriver                        0x0000000104ead00e chromedriver + 692238\n   11  chromedriver                        0x000000010527a9ad chromedriver + 4680109\n   12  chromedriver                        0x000000010527fc12 chromedriver + 4701202\n   13  chromedriver                        0x000000010528679f chromedriver + 4728735\n   14  chromedriver                        0x0000000105280b7a chromedriver + 4705146\n   15  chromedriver                        0x000000010525327e chromedriver + 4518526\n   16  chromedriver                        0x00000001052a0908 chromedriver + 4835592\n   17  chromedriver                        0x00000001052a0a87 chromedriver + 4835975\n   18  chromedriver                        0x00000001052b000f chromedriver + 4898831\n   19  libsystem_pthread.dylib             0x00007ff80f4a71d3 _pthread_start + 125\n   20  libsystem_pthread.dylib             0x00007ff80f4a2bd3 thread_start + 15\n       assert False\n", "test_name": "test_27_AksesMenuPusat", "rerun": "0"}, "27": {"status": "FAIL", "message": "           ConnectionRefusedError: [Errno 61] Connection refused\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x115b5abe0>: Failed to establish a new connection: [Errno 61] Connection refused\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=54795): Max retries exceeded with url: /session/073917622b14a658211660f9c89fedbe/timeouts (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x115b5abe0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n", "test_name": "test_28_PilihKanwil", "rerun": "0"}, "28": {"status": "FAIL", "message": "           ConnectionRefusedError: [Errno 61] Connection refused\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x115d4d1c0>: Failed to establish a new connection: [Errno 61] Connection refused\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=54795): Max retries exceeded with url: /session/073917622b14a658211660f9c89fedbe/timeouts (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x115d4d1c0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n", "test_name": "test_29_PilihUPT", "rerun": "0"}, "29": {"status": "FAIL", "message": "           ConnectionRefusedError: [Errno 61] Connection refused\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x115b68d00>: Failed to establish a new connection: [Errno 61] Connection refused\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=54795): Max retries exceeded with url: /session/073917622b14a658211660f9c89fedbe/timeouts (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x115b68d00>: Failed to establish a new connection: [Errno 61] Connection refused'))\n", "test_name": "test_30_ClickButtonSearch", "rerun": "0"}, "30": {"status": "FAIL", "message": "           ConnectionRefusedError: [Errno 61] Connection refused\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x115c95640>: Failed to establish a new connection: [Errno 61] Connection refused\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=54795): Max retries exceeded with url: /session/073917622b14a658211660f9c89fedbe/window (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x115c95640>: Failed to establish a new connection: [Errno 61] Connection refused'))\n", "test_name": "test_31_exit", "rerun": "0"}}, "suite_name": "4LaporanBulanan/12.Laporan8B/Fungsional/test_laporan8B.py"}}}, "date": "May 03, 2023", "start_time": 1683078152.6588109, "total_suite": 1, "status": "FAIL", "status_list": {"pass": "5", "fail": "26", "skip": "0", "error": "0", "xpass": "0", "xfail": "0", "rerun": "0"}, "total_tests": "31"}