{"content": {"suites": {"0": {"status": {"total_pass": 1, "total_skip": 0, "total_xpass": 0, "total_xfail": 0, "total_rerun": 0, "total_fail": 22, "total_error": 0}, "tests": {"0": {"status": "PASS", "message": "", "test_name": "test_1_setupOS", "rerun": "0"}, "1": {"status": "FAIL", "message": "       http.client.RemoteDisconnected: Remote end closed connection without response\n       urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))\n", "test_name": "test_2_login", "rerun": "0"}, "2": {"status": "FAIL", "message": "           ConnectionRefusedError: [Errno 61] Connection refused\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x102d6a250>: Failed to establish a new connection: [Errno 61] Connection refused\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=49198): Max retries exceeded with url: /session/1a2807ebd52b93ba960207da3f6bcf56/timeouts (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x102d6a250>: Failed to establish a new connection: [Errno 61] Connection refused'))\n", "test_name": "test_3_akses_menu_index", "rerun": "0"}, "3": {"status": "FAIL", "message": "           ConnectionRefusedError: [Errno 61] Connection refused\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x102cff8b0>: Failed to establish a new connection: [Errno 61] Connection refused\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=49198): Max retries exceeded with url: /session/1a2807ebd52b93ba960207da3f6bcf56/timeouts (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x102cff8b0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n", "test_name": "test_4_search_data_kategori_nama_Index", "rerun": "0"}, "4": {"status": "FAIL", "message": "           ConnectionRefusedError: [Errno 61] Connection refused\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x102e805b0>: Failed to establish a new connection: [Errno 61] Connection refused\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=49198): Max retries exceeded with url: /session/1a2807ebd52b93ba960207da3f6bcf56/timeouts (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x102e805b0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n", "test_name": "test_5_search_data_kategori_NoInduk_Index", "rerun": "0"}, "5": {"status": "FAIL", "message": "           ConnectionRefusedError: [Errno 61] Connection refused\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x102e57b50>: Failed to establish a new connection: [Errno 61] Connection refused\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=49198): Max retries exceeded with url: /session/1a2807ebd52b93ba960207da3f6bcf56/timeouts (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x102e57b50>: Failed to establish a new connection: [Errno 61] Connection refused'))\n", "test_name": "test_6_clik_clear_value_Index", "rerun": "0"}, "6": {"status": "FAIL", "message": "           ConnectionRefusedError: [Errno 61] Connection refused\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x102cb8160>: Failed to establish a new connection: [Errno 61] Connection refused\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=49198): Max retries exceeded with url: /session/1a2807ebd52b93ba960207da3f6bcf56/timeouts (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x102cb8160>: Failed to establish a new connection: [Errno 61] Connection refused'))\n", "test_name": "test_7_sortir_data_table_NoInduk_Index", "rerun": "0"}, "7": {"status": "FAIL", "message": "           ConnectionRefusedError: [Errno 61] Connection refused\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x102ac9430>: Failed to establish a new connection: [Errno 61] Connection refused\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=49198): Max retries exceeded with url: /session/1a2807ebd52b93ba960207da3f6bcf56/timeouts (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x102ac9430>: Failed to establish a new connection: [Errno 61] Connection refused'))\n", "test_name": "test_8_sortir_data_table_nama_Index", "rerun": "0"}, "8": {"status": "FAIL", "message": "           ConnectionRefusedError: [Errno 61] Connection refused\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x102b8d550>: Failed to establish a new connection: [Errno 61] Connection refused\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=49198): Max retries exceeded with url: /session/1a2807ebd52b93ba960207da3f6bcf56/timeouts (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x102b8d550>: Failed to establish a new connection: [Errno 61] Connection refused'))\n", "test_name": "test_9_sortir_data_table_Jenis_Index", "rerun": "0"}, "9": {"status": "FAIL", "message": "           ConnectionRefusedError: [Errno 61] Connection refused\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x102a9e520>: Failed to establish a new connection: [Errno 61] Connection refused\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=49198): Max retries exceeded with url: /session/1a2807ebd52b93ba960207da3f6bcf56/timeouts (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x102a9e520>: Failed to establish a new connection: [Errno 61] Connection refused'))\n", "test_name": "test_10_sortir_data_table_tglkeluar_Index", "rerun": "0"}, "10": {"status": "FAIL", "message": "           ConnectionRefusedError: [Errno 61] Connection refused\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x102e955e0>: Failed to establish a new connection: [Errno 61] Connection refused\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=49198): Max retries exceeded with url: /session/1a2807ebd52b93ba960207da3f6bcf56/timeouts (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x102e955e0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n", "test_name": "test_11_sortir_data_table_tglkembali_Index", "rerun": "0"}, "11": {"status": "FAIL", "message": "           ConnectionRefusedError: [Errno 61] Connection refused\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x102f5b2e0>: Failed to establish a new connection: [Errno 61] Connection refused\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=49198): Max retries exceeded with url: /session/1a2807ebd52b93ba960207da3f6bcf56/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x102f5b2e0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n", "test_name": "test_12_sortir_5_Halaman_Index", "rerun": "0"}, "12": {"status": "FAIL", "message": "           ConnectionRefusedError: [Errno 61] Connection refused\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x102a3ee80>: Failed to establish a new connection: [Errno 61] Connection refused\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=49198): Max retries exceeded with url: /session/1a2807ebd52b93ba960207da3f6bcf56/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x102a3ee80>: Failed to establish a new connection: [Errno 61] Connection refused'))\n", "test_name": "test_13_sortir_10_Halaman_Index", "rerun": "0"}, "13": {"status": "FAIL", "message": "           ConnectionRefusedError: [Errno 61] Connection refused\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x102b2d430>: Failed to establish a new connection: [Errno 61] Connection refused\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=49198): Max retries exceeded with url: /session/1a2807ebd52b93ba960207da3f6bcf56/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x102b2d430>: Failed to establish a new connection: [Errno 61] Connection refused'))\n", "test_name": "test_14_sortir_20_Halaman_Index", "rerun": "0"}, "14": {"status": "FAIL", "message": "           ConnectionRefusedError: [Errno 61] Connection refused\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x102f094f0>: Failed to establish a new connection: [Errno 61] Connection refused\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=49198): Max retries exceeded with url: /session/1a2807ebd52b93ba960207da3f6bcf56/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x102f094f0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n", "test_name": "test_15_sortir_50_Halaman_Index", "rerun": "0"}, "15": {"status": "FAIL", "message": "           ConnectionRefusedError: [Errno 61] Connection refused\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x102ef2370>: Failed to establish a new connection: [Errno 61] Connection refused\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=49198): Max retries exceeded with url: /session/1a2807ebd52b93ba960207da3f6bcf56/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x102ef2370>: Failed to establish a new connection: [Errno 61] Connection refused'))\n", "test_name": "test_16_sortir_100_Halaman_Index", "rerun": "0"}, "16": {"status": "FAIL", "message": "           ConnectionRefusedError: [Errno 61] Connection refused\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x102f98970>: Failed to establish a new connection: [Errno 61] Connection refused\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=49198): Max retries exceeded with url: /session/1a2807ebd52b93ba960207da3f6bcf56/timeouts (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x102f98970>: Failed to establish a new connection: [Errno 61] Connection refused'))\n", "test_name": "test_17_membuka_halaman_tambah_Index", "rerun": "0"}, "17": {"status": "FAIL", "message": "           ConnectionRefusedError: [Errno 61] Connection refused\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x102cfed30>: Failed to establish a new connection: [Errno 61] Connection refused\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=49198): Max retries exceeded with url: /session/1a2807ebd52b93ba960207da3f6bcf56/timeouts (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x102cfed30>: Failed to establish a new connection: [Errno 61] Connection refused'))\n", "test_name": "test_18_back_index", "rerun": "0"}, "18": {"status": "FAIL", "message": "           ConnectionRefusedError: [Errno 61] Connection refused\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x102efd2e0>: Failed to establish a new connection: [Errno 61] Connection refused\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=49198): Max retries exceeded with url: /session/1a2807ebd52b93ba960207da3f6bcf56/timeouts (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x102efd2e0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n", "test_name": "test_19_membuka_halaman_ubah_Index", "rerun": "0"}, "19": {"status": "FAIL", "message": "           ConnectionRefusedError: [Errno 61] Connection refused\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x102ddb490>: Failed to establish a new connection: [Errno 61] Connection refused\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=49198): Max retries exceeded with url: /session/1a2807ebd52b93ba960207da3f6bcf56/timeouts (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x102ddb490>: Failed to establish a new connection: [Errno 61] Connection refused'))\n", "test_name": "test_20_membuka_halaman_detail_Index", "rerun": "0"}, "20": {"status": "FAIL", "message": "           ConnectionRefusedError: [Errno 61] Connection refused\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x102ea2130>: Failed to establish a new connection: [Errno 61] Connection refused\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=49198): Max retries exceeded with url: /session/1a2807ebd52b93ba960207da3f6bcf56/timeouts (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x102ea2130>: Failed to establish a new connection: [Errno 61] Connection refused'))\n", "test_name": "test_21_export_exel_Index", "rerun": "0"}, "21": {"status": "FAIL", "message": "           ConnectionRefusedError: [Errno 61] Connection refused\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x102b74e50>: Failed to establish a new connection: [Errno 61] Connection refused\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=49198): Max retries exceeded with url: /session/1a2807ebd52b93ba960207da3f6bcf56/timeouts (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x102b74e50>: Failed to establish a new connection: [Errno 61] Connection refused'))\n", "test_name": "test_22_export_pdf_Index", "rerun": "0"}, "22": {"status": "FAIL", "message": "           ConnectionRefusedError: [Errno 61] Connection refused\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x102b0a1c0>: Failed to establish a new connection: [Errno 61] Connection refused\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=49198): Max retries exceeded with url: /session/1a2807ebd52b93ba960207da3f6bcf56/timeouts (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x102b0a1c0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n", "test_name": "test_23_cetak_Index", "rerun": "0"}}, "suite_name": "test_1Fungsi_Daftar_Lalu_Lintas_Index.py"}, "1": {"suite_name": "test_2Fungsi_Daftar_Lalu_Lintas_Cari_Identitas.py", "tests": {"0": {"status": "PASS", "message": "", "test_name": "test_1_setupOS", "rerun": "0"}, "1": {"status": "PASS", "message": "", "test_name": "test_2_login", "rerun": "0"}, "2": {"status": "PASS", "message": "", "test_name": "test_3_akses_menu_index", "rerun": "0"}, "3": {"status": "PASS", "message": "", "test_name": "test_4_membuka_halaman_tambah_index", "rerun": "0"}, "4": {"status": "PASS", "message": "", "test_name": "test_5_Button_Next_Prev", "rerun": "0"}, "5": {"status": "PASS", "message": "", "test_name": "test_6_sortir_table_cari_noreg_cari_identitas", "rerun": "0"}, "6": {"status": "PASS", "message": "", "test_name": "test_7_sortir_table_cari_nama_cari_identitas", "rerun": "0"}, "7": {"status": "PASS", "message": "", "test_name": "test_8_sortir_table_cari_JenisKejahatan_cari_identitas", "rerun": "0"}, "8": {"status": "PASS", "message": "", "test_name": "test_9_search_data_aktif_cari_identitas", "rerun": "0"}, "9": {"status": "PASS", "message": "", "test_name": "test_10_search_residivis_cari_identitas", "rerun": "0"}, "10": {"status": "PASS", "message": "", "test_name": "test_11_Sortir_5_Halaman_cari_identitas", "rerun": "0"}, "11": {"status": "PASS", "message": "", "test_name": "test_12_sortir_10_Halaman_cari_identitas", "rerun": "0"}, "12": {"status": "PASS", "message": "", "test_name": "test_13_sortir_20_Halaman_cari_identitas", "rerun": "0"}, "13": {"status": "PASS", "message": "", "test_name": "test_14_sortir_50_Halaman_cari_identitas", "rerun": "0"}, "14": {"status": "PASS", "message": "", "test_name": "test_15_sortir_100_Halaman_cari_identitas", "rerun": "0"}}, "status": {"total_pass": 15, "total_skip": 0, "total_xpass": 0, "total_xfail": 0, "total_rerun": 0, "total_fail": 0, "total_error": 0}}, "2": {"suite_name": "test_3Fungsi_Daftar_Lalu_Lintas_Tambah.py", "tests": {"0": {"status": "PASS", "message": "", "test_name": "test_1_setupOS_HalamanTambah", "rerun": "0"}, "1": {"status": "PASS", "message": "", "test_name": "test_2_login_HalamanTambah", "rerun": "0"}, "2": {"status": "PASS", "message": "", "test_name": "test_3_akses_menu_HalamanTambah", "rerun": "0"}, "3": {"status": "PASS", "message": "", "test_name": "test_4_membuka_halaman_HalamanTambah", "rerun": "0"}, "4": {"status": "PASS", "message": "", "test_name": "test_5_sortir_table_cari_nama_HalamanTambah", "rerun": "0"}, "5": {"status": "PASS", "message": "", "test_name": "test_6_Click_Button_Detile_HalamanTambah", "rerun": "0"}, "6": {"status": "PASS", "message": "", "test_name": "test_7_Click_Button_Tambah_WBP_HalamanTambah", "rerun": "0"}, "7": {"status": "PASS", "message": "", "test_name": "test_8_sortir_detil_wbp_HalamanTambah", "rerun": "0"}, "8": {"status": "PASS", "message": "", "test_name": "test_9_detile_perkara_HalamanTambah", "rerun": "0"}, "9": {"status": "PASS", "message": "", "test_name": "test_10_Input_JenisKeluar_HalamanTambah", "rerun": "0"}, "10": {"status": "PASS", "message": "", "test_name": "test_11_Input_Tanggal_Keluar_HalamanTambah", "rerun": "0"}, "11": {"status": "PASS", "message": "", "test_name": "test_12_Input_Deskripsi_HalamanTambah", "rerun": "0"}, "12": {"status": "PASS", "message": "", "test_name": "test_13_Input_Tanggal_Harus_Kembali_HalamanTambah", "rerun": "0"}, "13": {"status": "PASS", "message": "", "test_name": "test_14_tambah_Pengwal_HalamanTambah", "rerun": "0"}, "14": {"status": "PASS", "message": "", "test_name": "test_15_JenisPengawal_HalamanTambah", "rerun": "0"}, "15": {"status": "PASS", "message": "", "test_name": "test_16_NamaPengawalInternal_HalamanTambah", "rerun": "0"}, "16": {"status": "PASS", "message": "", "test_name": "test_17_ButtonSubmitInternal_HalamanTambah", "rerun": "0"}}, "status": {"total_pass": 17, "total_skip": 0, "total_xpass": 0, "total_xfail": 0, "total_rerun": 0, "total_fail": 0, "total_error": 0}}, "3": {"suite_name": "test_4Fungsi_Daftar_Lalu_Lintas_Edit.py", "tests": {"0": {"status": "PASS", "message": "", "test_name": "test_1_setupOS", "rerun": "0"}, "1": {"status": "PASS", "message": "", "test_name": "test_2_login_HalamanEdit", "rerun": "0"}, "2": {"status": "PASS", "message": "", "test_name": "test_3_akses_menu_HalamanEdit", "rerun": "0"}, "3": {"status": "PASS", "message": "", "test_name": "test_4_Click_ButtonUbah_HalamanEdit", "rerun": "0"}, "4": {"status": "PASS", "message": "", "test_name": "test_5__sortir_detil_wbp_HalamanEdit", "rerun": "0"}, "5": {"status": "PASS", "message": "", "test_name": "test_6_detile_perkara_HalamanEdit", "rerun": "0"}, "6": {"status": "PASS", "message": "", "test_name": "test_7_Muat_Ulang_HalamanEdit", "rerun": "0"}, "7": {"status": "PASS", "message": "", "test_name": "test_8_Ubah_Deskripsi_HalamanEdit", "rerun": "0"}}, "status": {"total_pass": 8, "total_skip": 0, "total_xpass": 0, "total_xfail": 0, "total_rerun": 0, "total_fail": 0, "total_error": 0}}}}, "date": "November 10, 2022", "start_time": 1668047327.91348, "total_suite": 4, "status": "FAIL", "status_list": {"pass": "41", "fail": "22", "skip": "0", "error": "0", "xpass": "0", "xfail": "0", "rerun": "0"}, "total_tests": "63"}