{"content": {"suites": {"0": {"status": {"total_pass": 1, "total_skip": 0, "total_xpass": 0, "total_xfail": 0, "total_rerun": 0, "total_fail": 9, "total_error": 0}, "tests": {"0": {"status": "PASS", "message": "", "test_name": "test_1_SetupOs", "rerun": "0"}, "1": {"status": "FAIL", "message": "   selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {\"method\":\"css selector\",\"selector\":\"[id=\"login\"]\"}\n     (Session info: chrome=112.0.5615.49)\n   Stacktrace:\n   0   chromedriver                        0x0000000100618ae8 chromedriver + 4958952\n   1   chromedriver                        0x00000001006107b3 chromedriver + 4925363\n   2   chromedriver                        0x00000001001d21d6 chromedriver + 475606\n   3   chromedriver                        0x0000000100215a20 chromedriver + 752160\n   4   chromedriver                        0x0000000100215c81 chromedriver + 752769\n   5   chromedriver                        0x0000000100259f64 chromedriver + 1032036\n   6   chromedriver                        0x000000010023bc3d chromedriver + 908349\n   7   chromedriver                        0x000000010025725b chromedriver + 1020507\n   8   chromedriver                        0x000000010023b9e3 chromedriver + 907747\n   9   chromedriver                        0x0000000100205aef chromedriver + 686831\n   10  chromedriver                        0x000000010020700e chromedriver + 692238\n   11  chromedriver                        0x00000001005d49ad chromedriver + 4680109\n   12  chromedriver                        0x00000001005d9c12 chromedriver + 4701202\n   13  chromedriver                        0x00000001005e079f chromedriver + 4728735\n   14  chromedriver                        0x00000001005dab7a chromedriver + 4705146\n   15  chromedriver                        0x00000001005ad27e chromedriver + 4518526\n   16  chromedriver                        0x00000001005fa908 chromedriver + 4835592\n   17  chromedriver                        0x00000001005faa87 chromedriver + 4835975\n   18  chromedriver                        0x000000010060a00f chromedriver + 4898831\n   19  libsystem_pthread.dylib             0x00007ff8173931d3 _pthread_start + 125\n   20  libsystem_pthread.dylib             0x00007ff81738ebd3 thread_start + 15\n", "test_name": "test_2_Login", "rerun": "0"}, "2": {"status": "FAIL", "message": "   selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {\"method\":\"css selector\",\"selector\":\"[id=\"KEA00\"]\"}\n     (Session info: chrome=112.0.5615.49)\n   Stacktrace:\n   0   chromedriver                        0x0000000100618ae8 chromedriver + 4958952\n   1   chromedriver                        0x00000001006107b3 chromedriver + 4925363\n   2   chromedriver                        0x00000001001d21d6 chromedriver + 475606\n   3   chromedriver                        0x0000000100215a20 chromedriver + 752160\n   4   chromedriver                        0x0000000100215c81 chromedriver + 752769\n   5   chromedriver                        0x0000000100259f64 chromedriver + 1032036\n   6   chromedriver                        0x000000010023bc3d chromedriver + 908349\n   7   chromedriver                        0x000000010025725b chromedriver + 1020507\n   8   chromedriver                        0x000000010023b9e3 chromedriver + 907747\n   9   chromedriver                        0x0000000100205aef chromedriver + 686831\n   10  chromedriver                        0x000000010020700e chromedriver + 692238\n   11  chromedriver                        0x00000001005d49ad chromedriver + 4680109\n   12  chromedriver                        0x00000001005d9c12 chromedriver + 4701202\n   13  chromedriver                        0x00000001005e079f chromedriver + 4728735\n   14  chromedriver                        0x00000001005dab7a chromedriver + 4705146\n   15  chromedriver                        0x00000001005ad27e chromedriver + 4518526\n   16  chromedriver                        0x00000001005fa908 chromedriver + 4835592\n   17  chromedriver                        0x00000001005faa87 chromedriver + 4835975\n   18  chromedriver                        0x000000010060a00f chromedriver + 4898831\n   19  libsystem_pthread.dylib             0x00007ff8173931d3 _pthread_start + 125\n   20  libsystem_pthread.dylib             0x00007ff81738ebd3 thread_start + 15\n       assert False\n", "test_name": "test_2_AksesMenu", "rerun": "0"}, "3": {"status": "FAIL", "message": "           ConnectionRefusedError: [Errno 61] Connection refused\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x12a7a7430>: Failed to establish a new connection: [Errno 61] Connection refused\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=58222): Max retries exceeded with url: /session/3445b217d2570e1e9eb5533f079aeec0/timeouts (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x12a7a7430>: Failed to establish a new connection: [Errno 61] Connection refused'))\n", "test_name": "test_3_CreateButton", "rerun": "0"}, "4": {"status": "FAIL", "message": "           ConnectionRefusedError: [Errno 61] Connection refused\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x12ad1f0d0>: Failed to establish a new connection: [Errno 61] Connection refused\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=58222): Max retries exceeded with url: /session/3445b217d2570e1e9eb5533f079aeec0/timeouts (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x12ad1f0d0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n", "test_name": "test_3_SearchWBP", "rerun": "0"}, "5": {"status": "FAIL", "message": "           ConnectionRefusedError: [Errno 61] Connection refused\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x12a798cd0>: Failed to establish a new connection: [Errno 61] Connection refused\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=58222): Max retries exceeded with url: /session/3445b217d2570e1e9eb5533f079aeec0/timeouts (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x12a798cd0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n", "test_name": "test_4_PilihJenisGangguan", "rerun": "0"}, "6": {"status": "FAIL", "message": "           ConnectionRefusedError: [Errno 61] Connection refused\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x12ad83b50>: Failed to establish a new connection: [Errno 61] Connection refused\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=58222): Max retries exceeded with url: /session/3445b217d2570e1e9eb5533f079aeec0/timeouts (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x12ad83b50>: Failed to establish a new connection: [Errno 61] Connection refused'))\n", "test_name": "test_5_ClickButtonDaftarkan", "rerun": "0"}, "7": {"status": "FAIL", "message": "           ConnectionRefusedError: [Errno 61] Connection refused\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x12abb1280>: Failed to establish a new connection: [Errno 61] Connection refused\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=58222): Max retries exceeded with url: /session/3445b217d2570e1e9eb5533f079aeec0/timeouts (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x12abb1280>: Failed to establish a new connection: [Errno 61] Connection refused'))\n", "test_name": "test_6_InputData", "rerun": "0"}, "8": {"status": "FAIL", "message": "           ConnectionRefusedError: [Errno 61] Connection refused\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x12aa7d2b0>: Failed to establish a new connection: [Errno 61] Connection refused\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=58222): Max retries exceeded with url: /session/3445b217d2570e1e9eb5533f079aeec0/timeouts (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x12aa7d2b0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n", "test_name": "test_7_submit", "rerun": "0"}, "9": {"status": "FAIL", "message": "           ConnectionRefusedError: [Errno 61] Connection refused\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x12ae147f0>: Failed to establish a new connection: [Errno 61] Connection refused\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=58222): Max retries exceeded with url: /session/3445b217d2570e1e9eb5533f079aeec0/window (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x12ae147f0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n", "test_name": "test_8_exit", "rerun": "0"}}, "suite_name": "4LaporanBulanan/10.Laporan7D/Fungsional/test_Laporan7D.py"}}}, "date": "April 13, 2023", "start_time": 1681401187.636537, "total_suite": 1, "status": "FAIL", "status_list": {"pass": "1", "fail": "9", "skip": "0", "error": "0", "xpass": "0", "xfail": "0", "rerun": "0"}, "total_tests": "10"}