{"content": {"suites": {"0": {"status": {"total_pass": 9, "total_skip": 0, "total_xpass": 0, "total_xfail": 0, "total_rerun": 0, "total_fail": 6, "total_error": 0}, "tests": {"0": {"status": "PASS", "message": "", "test_name": "test_1_SetupOs", "rerun": "0"}, "1": {"status": "PASS", "message": "", "test_name": "test_2_Login", "rerun": "0"}, "2": {"status": "PASS", "message": "", "test_name": "test_2_AksesMenu", "rerun": "0"}, "3": {"status": "PASS", "message": "", "test_name": "test_3_CreateButton", "rerun": "0"}, "4": {"status": "PASS", "message": "", "test_name": "test_4_InputLuasUpt", "rerun": "0"}, "5": {"status": "PASS", "message": "", "test_name": "test_5_InputKapasitasHunian", "rerun": "0"}, "6": {"status": "PASS", "message": "", "test_name": "test_6_InputLuasBlok", "rerun": "0"}, "7": {"status": "PASS", "message": "", "test_name": "test_7_InputJumlahPenghuni", "rerun": "0"}, "8": {"status": "PASS", "message": "", "test_name": "test_8_InputKamarLayak", "rerun": "0"}, "9": {"status": "FAIL", "message": "           TypeError: object of type 'NoneType' has no len()\n       assert False\n", "test_name": "test_9_InputKamarTidakLayak", "rerun": "0"}, "10": {"status": "FAIL", "message": "           ConnectionRefusedError: [Errno 61] Connection refused\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x105dfe3a0>: Failed to establish a new connection: [Errno 61] Connection refused\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=52158): Max retries exceeded with url: /session/e0e7fdf01d517d0a17101d0d61c50f5f/timeouts (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x105dfe3a0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n", "test_name": "test_10_InputVentilasiLayak", "rerun": "0"}, "11": {"status": "FAIL", "message": "           ConnectionRefusedError: [Errno 61] Connection refused\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x1061f7040>: Failed to establish a new connection: [Errno 61] Connection refused\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=52158): Max retries exceeded with url: /session/e0e7fdf01d517d0a17101d0d61c50f5f/timeouts (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1061f7040>: Failed to establish a new connection: [Errno 61] Connection refused'))\n", "test_name": "test_10_InputVentilasiTidakLayak", "rerun": "0"}, "12": {"status": "FAIL", "message": "           ConnectionRefusedError: [Errno 61] Connection refused\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x1061b9160>: Failed to establish a new connection: [Errno 61] Connection refused\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=52158): Max retries exceeded with url: /session/e0e7fdf01d517d0a17101d0d61c50f5f/timeouts (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1061b9160>: Failed to establish a new connection: [Errno 61] Connection refused'))\n", "test_name": "test_11_InputAirLayak", "rerun": "0"}, "13": {"status": "FAIL", "message": "           ConnectionRefusedError: [Errno 61] Connection refused\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x105f48c70>: Failed to establish a new connection: [Errno 61] Connection refused\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=52158): Max retries exceeded with url: /session/e0e7fdf01d517d0a17101d0d61c50f5f/timeouts (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x105f48c70>: Failed to establish a new connection: [Errno 61] Connection refused'))\n", "test_name": "test_12_InputPencahayaanLayak", "rerun": "0"}, "14": {"status": "FAIL", "message": "           ConnectionRefusedError: [Errno 61] Connection refused\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x10635d190>: Failed to establish a new connection: [Errno 61] Connection refused\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=52158): Max retries exceeded with url: /session/e0e7fdf01d517d0a17101d0d61c50f5f/window (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10635d190>: Failed to establish a new connection: [Errno 61] Connection refused'))\n", "test_name": "test_37_exit", "rerun": "0"}}, "suite_name": "4LaporanBulanan/4.Laporan6F/Fungsional/test_Laporan6F.py"}}}, "date": "April 12, 2023", "start_time": 1681268995.80425, "total_suite": 1, "status": "FAIL", "status_list": {"pass": "9", "fail": "6", "skip": "0", "error": "0", "xpass": "0", "xfail": "0", "rerun": "0"}, "total_tests": "15"}