{"content": {"suites": {"0": {"status": {"total_pass": 14, "total_skip": 0, "total_xpass": 0, "total_xfail": 0, "total_rerun": 0, "total_fail": 6, "total_error": 0}, "tests": {"0": {"status": "PASS", "message": "", "test_name": "test_1_SetupOs", "rerun": "0"}, "1": {"status": "PASS", "message": "", "test_name": "test_2_Login", "rerun": "0"}, "2": {"status": "PASS", "message": "", "test_name": "test_3_AksesMenu", "rerun": "0"}, "3": {"status": "PASS", "message": "", "test_name": "test_4_ClickButtonTambah", "rerun": "0"}, "4": {"status": "PASS", "message": "", "test_name": "test_5_InputBidangGiatja", "rerun": "0"}, "5": {"status": "PASS", "message": "", "test_name": "test_6_InputJenisKegiatanKerja", "rerun": "0"}, "6": {"status": "PASS", "message": "", "test_name": "test_7_namaKegiatan", "rerun": "0"}, "7": {"status": "PASS", "message": "", "test_name": "test_8_skalaKegiatan", "rerun": "0"}, "8": {"status": "PASS", "message": "", "test_name": "test_9_tanggalAwalKegiatan", "rerun": "0"}, "9": {"status": "PASS", "message": "", "test_name": "test_10_tanggalAkhirKegiatan", "rerun": "0"}, "10": {"status": "PASS", "message": "", "test_name": "test_11_AreaKegiatan", "rerun": "0"}, "11": {"status": "PASS", "message": "", "test_name": "test_12_lokasiKegiatan", "rerun": "0"}, "12": {"status": "PASS", "message": "", "test_name": "test_13_luas", "rerun": "0"}, "13": {"status": "PASS", "message": "", "test_name": "test_14_jumlahRuang", "rerun": "0"}, "14": {"status": "FAIL", "message": "   selenium.common.exceptions.TimeoutException: Message: \n   Stacktrace:\n   0   chromedriver                        0x0000000103188ae8 chromedriver + 4958952\n   1   chromedriver                        0x00000001031807b3 chromedriver + 4925363\n   2   chromedriver                        0x0000000102d421d6 chromedriver + 475606\n   3   chromedriver                        0x0000000102d85a20 chromedriver + 752160\n   4   chromedriver                        0x0000000102d85c81 chromedriver + 752769\n   5   chromedriver                        0x0000000102dc9f64 chromedriver + 1032036\n   6   chromedriver                        0x0000000102dabc3d chromedriver + 908349\n   7   chromedriver                        0x0000000102dc725b chromedriver + 1020507\n   8   chromedriver                        0x0000000102dab9e3 chromedriver + 907747\n   9   chromedriver                        0x0000000102d75aef chromedriver + 686831\n   10  chromedriver                        0x0000000102d7700e chromedriver + 692238\n   11  chromedriver                        0x00000001031449ad chromedriver + 4680109\n   12  chromedriver                        0x0000000103149c12 chromedriver + 4701202\n   13  chromedriver                        0x000000010315079f chromedriver + 4728735\n   14  chromedriver                        0x000000010314ab7a chromedriver + 4705146\n   15  chromedriver                        0x000000010311d27e chromedriver + 4518526\n   16  chromedriver                        0x000000010316a908 chromedriver + 4835592\n   17  chromedriver                        0x000000010316aa87 chromedriver + 4835975\n   18  chromedriver                        0x000000010317a00f chromedriver + 4898831\n   19  libsystem_pthread.dylib             0x00007ff8161cb1d3 _pthread_start + 125\n   20  libsystem_pthread.dylib             0x00007ff8161c6bd3 thread_start + 15\n       assert False\n", "test_name": "test_15_sarana", "rerun": "0"}, "15": {"status": "FAIL", "message": "           ConnectionRefusedError: [Errno 61] Connection refused\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x117ed24f0>: Failed to establish a new connection: [Errno 61] Connection refused\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=56645): Max retries exceeded with url: /session/382febe952bfe73fbc5f85b55b9ed7fa/timeouts (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x117ed24f0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n", "test_name": "test_16_prasarana", "rerun": "0"}, "16": {"status": "FAIL", "message": "           ConnectionRefusedError: [Errno 61] Connection refused\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x140e56b50>: Failed to establish a new connection: [Errno 61] Connection refused\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=56645): Max retries exceeded with url: /session/382febe952bfe73fbc5f85b55b9ed7fa/timeouts (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x140e56b50>: Failed to establish a new connection: [Errno 61] Connection refused'))\n", "test_name": "test_17_mitra", "rerun": "0"}, "17": {"status": "FAIL", "message": "           ConnectionRefusedError: [Errno 61] Connection refused\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x140f31be0>: Failed to establish a new connection: [Errno 61] Connection refused\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=56645): Max retries exceeded with url: /session/382febe952bfe73fbc5f85b55b9ed7fa/timeouts (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x140f31be0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n", "test_name": "test_18_InputGambar", "rerun": "0"}, "18": {"status": "FAIL", "message": "           ConnectionRefusedError: [Errno 61] Connection refused\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x140f7ea30>: Failed to establish a new connection: [Errno 61] Connection refused\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=56645): Max retries exceeded with url: /session/382febe952bfe73fbc5f85b55b9ed7fa/timeouts (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x140f7ea30>: Failed to establish a new connection: [Errno 61] Connection refused'))\n", "test_name": "test_19_Keterangan", "rerun": "0"}, "19": {"status": "FAIL", "message": "           ConnectionRefusedError: [Errno 61] Connection refused\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x1430202b0>: Failed to establish a new connection: [Errno 61] Connection refused\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=56645): Max retries exceeded with url: /session/382febe952bfe73fbc5f85b55b9ed7fa/window (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1430202b0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n", "test_name": "test_32_exit", "rerun": "0"}}, "suite_name": "1.KegiatanKerja/Fungsional/test_GiatjaTambah.py"}}}, "date": "May 02, 2023", "start_time": 1683012588.3635, "total_suite": 1, "status": "FAIL", "status_list": {"pass": "14", "fail": "6", "skip": "0", "error": "0", "xpass": "0", "xfail": "0", "rerun": "0"}, "total_tests": "20"}