{"content": {"suites": {"0": {"status": {"total_pass": 1, "total_skip": 0, "total_xpass": 0, "total_xfail": 0, "total_rerun": 0, "total_fail": 19, "total_error": 0}, "tests": {"0": {"status": "PASS", "message": "", "test_name": "test_1_setupOS_HalamanTambah", "rerun": "0"}, "1": {"status": "FAIL", "message": "   selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {\"method\":\"xpath\",\"selector\":\"//div/span\"}\n     (Session info: chrome=108.0.5359.71)\n   Stacktrace:\n   0   chromedriver                        0x00000001046d6a88 chromedriver + 4123272\n   1   chromedriver                        0x0000000104662778 chromedriver + 3647352\n   2   chromedriver                        0x0000000104324ac4 chromedriver + 248516\n   3   chromedriver                        0x000000010435af68 chromedriver + 470888\n   4   chromedriver                        0x000000010438d020 chromedriver + 675872\n   5   chromedriver                        0x000000010434eb10 chromedriver + 420624\n   6   chromedriver                        0x000000010434fc30 chromedriver + 425008\n   7   chromedriver                        0x00000001046a8ae4 chromedriver + 3934948\n   8   chromedriver                        0x00000001046abf24 chromedriver + 3948324\n   9   chromedriver                        0x00000001046ac508 chromedriver + 3949832\n   10  chromedriver                        0x00000001046b2b30 chromedriver + 3975984\n   11  chromedriver                        0x00000001046acb24 chromedriver + 3951396\n   12  chromedriver                        0x000000010468771c chromedriver + 3798812\n   13  chromedriver                        0x00000001046c92f0 chromedriver + 4068080\n   14  chromedriver                        0x00000001046c9444 chromedriver + 4068420\n   15  chromedriver                        0x00000001046dd450 chromedriver + 4150352\n   16  libsystem_pthread.dylib             0x00000001a497206c _pthread_start + 148\n   17  libsystem_pthread.dylib             0x00000001a496ce2c thread_start + 8\n", "test_name": "test_2_login_HalamanTambah", "rerun": "0"}, "2": {"status": "FAIL", "message": "       http.client.RemoteDisconnected: Remote end closed connection without response\n       urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))\n", "test_name": "test_3_akses_menu_HalamanTambah", "rerun": "0"}, "3": {"status": "FAIL", "message": "           ConnectionRefusedError: [Errno 61] Connection refused\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x10bc74820>: Failed to establish a new connection: [Errno 61] Connection refused\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=59470): Max retries exceeded with url: /session/b8b311275f37914eff0fe64a9f7db4ec/timeouts (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10bc74820>: Failed to establish a new connection: [Errno 61] Connection refused'))\n", "test_name": "test_4_membuka_halaman_HalamanTambah", "rerun": "0"}, "4": {"status": "FAIL", "message": "           ConnectionRefusedError: [Errno 61] Connection refused\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x11eaa92b0>: Failed to establish a new connection: [Errno 61] Connection refused\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=59470): Max retries exceeded with url: /session/b8b311275f37914eff0fe64a9f7db4ec/timeouts (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11eaa92b0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n", "test_name": "test_5_sortir_table_cari_nama_HalamanTambah", "rerun": "0"}, "5": {"status": "FAIL", "message": "           ConnectionRefusedError: [Errno 61] Connection refused\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x11eaa64c0>: Failed to establish a new connection: [Errno 61] Connection refused\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=59470): Max retries exceeded with url: /session/b8b311275f37914eff0fe64a9f7db4ec/timeouts (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11eaa64c0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n", "test_name": "test_6_Click_Button_Detile_HalamanTambah", "rerun": "0"}, "6": {"status": "FAIL", "message": "           ConnectionRefusedError: [Errno 61] Connection refused\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x10bcce310>: Failed to establish a new connection: [Errno 61] Connection refused\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=59470): Max retries exceeded with url: /session/b8b311275f37914eff0fe64a9f7db4ec/timeouts (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10bcce310>: Failed to establish a new connection: [Errno 61] Connection refused'))\n", "test_name": "test_7_Click_Button_Tambah_WBP_HalamanTambah", "rerun": "0"}, "7": {"status": "FAIL", "message": "           ConnectionRefusedError: [Errno 61] Connection refused\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x10bb27f10>: Failed to establish a new connection: [Errno 61] Connection refused\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=59470): Max retries exceeded with url: /session/b8b311275f37914eff0fe64a9f7db4ec/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10bb27f10>: Failed to establish a new connection: [Errno 61] Connection refused'))\n", "test_name": "test_8_sortir_detil_wbp_HalamanTambah", "rerun": "0"}, "8": {"status": "FAIL", "message": "           ConnectionRefusedError: [Errno 61] Connection refused\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x10bb52df0>: Failed to establish a new connection: [Errno 61] Connection refused\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=59470): Max retries exceeded with url: /session/b8b311275f37914eff0fe64a9f7db4ec/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10bb52df0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n", "test_name": "test_9_detile_perkara_HalamanTambah", "rerun": "0"}, "9": {"status": "FAIL", "message": "           ConnectionRefusedError: [Errno 61] Connection refused\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x10bdc55e0>: Failed to establish a new connection: [Errno 61] Connection refused\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=59470): Max retries exceeded with url: /session/b8b311275f37914eff0fe64a9f7db4ec/timeouts (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10bdc55e0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n", "test_name": "test_10_Input_JenisKeluar_HalamanTambah", "rerun": "0"}, "10": {"status": "FAIL", "message": "           ConnectionRefusedError: [Errno 61] Connection refused\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x10bb34520>: Failed to establish a new connection: [Errno 61] Connection refused\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=59470): Max retries exceeded with url: /session/b8b311275f37914eff0fe64a9f7db4ec/timeouts (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10bb34520>: Failed to establish a new connection: [Errno 61] Connection refused'))\n", "test_name": "test_11_Input_Tanggal_Keluar_HalamanTambah", "rerun": "0"}, "11": {"status": "FAIL", "message": "           ConnectionRefusedError: [Errno 61] Connection refused\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x10bcd73d0>: Failed to establish a new connection: [Errno 61] Connection refused\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=59470): Max retries exceeded with url: /session/b8b311275f37914eff0fe64a9f7db4ec/timeouts (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10bcd73d0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n", "test_name": "test_12_Input_Deskripsi_HalamanTambah", "rerun": "0"}, "12": {"status": "FAIL", "message": "           ConnectionRefusedError: [Errno 61] Connection refused\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x10bca4370>: Failed to establish a new connection: [Errno 61] Connection refused\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=59470): Max retries exceeded with url: /session/b8b311275f37914eff0fe64a9f7db4ec/timeouts (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10bca4370>: Failed to establish a new connection: [Errno 61] Connection refused'))\n", "test_name": "test_13_Input_Tanggal_Harus_Kembali_HalamanTambah", "rerun": "0"}, "13": {"status": "FAIL", "message": "           ConnectionRefusedError: [Errno 61] Connection refused\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x10bb7f550>: Failed to establish a new connection: [Errno 61] Connection refused\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=59470): Max retries exceeded with url: /session/b8b311275f37914eff0fe64a9f7db4ec/timeouts (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10bb7f550>: Failed to establish a new connection: [Errno 61] Connection refused'))\n", "test_name": "test_14_tambah_Pengwal_HalamanTambah", "rerun": "0"}, "14": {"status": "FAIL", "message": "           ConnectionRefusedError: [Errno 61] Connection refused\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x11eb32790>: Failed to establish a new connection: [Errno 61] Connection refused\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=59470): Max retries exceeded with url: /session/b8b311275f37914eff0fe64a9f7db4ec/timeouts (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11eb32790>: Failed to establish a new connection: [Errno 61] Connection refused'))\n", "test_name": "test_15_JenisPengawal_HalamanTambah", "rerun": "0"}, "15": {"status": "FAIL", "message": "           ConnectionRefusedError: [Errno 61] Connection refused\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x11eb1ba30>: Failed to establish a new connection: [Errno 61] Connection refused\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=59470): Max retries exceeded with url: /session/b8b311275f37914eff0fe64a9f7db4ec/timeouts (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11eb1ba30>: Failed to establish a new connection: [Errno 61] Connection refused'))\n", "test_name": "test_16_NamaPengawalInternal_HalamanTambah", "rerun": "0"}, "16": {"status": "FAIL", "message": "           ConnectionRefusedError: [Errno 61] Connection refused\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x10bba2d60>: Failed to establish a new connection: [Errno 61] Connection refused\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=59470): Max retries exceeded with url: /session/b8b311275f37914eff0fe64a9f7db4ec/timeouts (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10bba2d60>: Failed to establish a new connection: [Errno 61] Connection refused'))\n", "test_name": "test_17_JenisPengawalEksternal_HalamanTambah", "rerun": "0"}, "17": {"status": "FAIL", "message": "           ConnectionRefusedError: [Errno 61] Connection refused\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x11ea2dbb0>: Failed to establish a new connection: [Errno 61] Connection refused\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=59470): Max retries exceeded with url: /session/b8b311275f37914eff0fe64a9f7db4ec/timeouts (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11ea2dbb0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n", "test_name": "test_18_NamaPengawalEksternal_HalamanTambah", "rerun": "0"}, "18": {"status": "FAIL", "message": "           ConnectionRefusedError: [Errno 61] Connection refused\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x11eb71af0>: Failed to establish a new connection: [Errno 61] Connection refused\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=59470): Max retries exceeded with url: /session/b8b311275f37914eff0fe64a9f7db4ec/timeouts (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11eb71af0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n", "test_name": "test_19_ButtonSubmitInternal_HalamanTambah", "rerun": "0"}, "19": {"status": "FAIL", "message": "           ConnectionRefusedError: [Errno 61] Connection refused\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x11ea39430>: Failed to establish a new connection: [Errno 61] Connection refused\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=59470): Max retries exceeded with url: /session/b8b311275f37914eff0fe64a9f7db4ec/window (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11ea39430>: Failed to establish a new connection: [Errno 61] Connection refused'))\n", "test_name": "test_exit", "rerun": "0"}}, "suite_name": "test_3Fungsi_Daftar_Lalu_Lintas_Tambah.py"}}}, "date": "November 30, 2022", "start_time": 1669810826.850935, "total_suite": 1, "status": "FAIL", "status_list": {"pass": "1", "fail": "19", "skip": "0", "error": "0", "xpass": "0", "xfail": "0", "rerun": "0"}, "total_tests": "20"}