{"content": {"suites": {"0": {"status": {"total_pass": 3, "total_skip": 0, "total_xpass": 0, "total_xfail": 0, "total_rerun": 0, "total_fail": 3, "total_error": 0}, "tests": {"0": {"status": "PASS", "message": "", "test_name": "test_1_SetupOs", "rerun": "0"}, "1": {"status": "PASS", "message": "", "test_name": "test_2_Login", "rerun": "0"}, "2": {"status": "PASS", "message": "", "test_name": "test_2_AksesMenu", "rerun": "0"}, "3": {"status": "FAIL", "message": "   AttributeError: module 'selenium.webdriver.support.expected_conditions' has no attribute 'element_to_be_\u00e7\u00e7clickable'\n", "test_name": "test_3_CreateButton", "rerun": "0"}, "4": {"status": "FAIL", "message": "   selenium.common.exceptions.TimeoutException: Message: \n   Stacktrace:\n   0   chromedriver                        0x000000010061eae8 chromedriver + 4958952\n   1   chromedriver                        0x00000001006167b3 chromedriver + 4925363\n   2   chromedriver                        0x00000001001d81d6 chromedriver + 475606\n   3   chromedriver                        0x000000010021ba20 chromedriver + 752160\n   4   chromedriver                        0x000000010021bc81 chromedriver + 752769\n   5   chromedriver                        0x000000010025ff64 chromedriver + 1032036\n   6   chromedriver                        0x0000000100241c3d chromedriver + 908349\n   7   chromedriver                        0x000000010025d25b chromedriver + 1020507\n   8   chromedriver                        0x00000001002419e3 chromedriver + 907747\n   9   chromedriver                        0x000000010020baef chromedriver + 686831\n   10  chromedriver                        0x000000010020d00e chromedriver + 692238\n   11  chromedriver                        0x00000001005da9ad chromedriver + 4680109\n   12  chromedriver                        0x00000001005dfc12 chromedriver + 4701202\n   13  chromedriver                        0x00000001005e679f chromedriver + 4728735\n   14  chromedriver                        0x00000001005e0b7a chromedriver + 4705146\n   15  chromedriver                        0x00000001005b327e chromedriver + 4518526\n   16  chromedriver                        0x0000000100600908 chromedriver + 4835592\n   17  chromedriver                        0x0000000100600a87 chromedriver + 4835975\n   18  chromedriver                        0x000000010061000f chromedriver + 4898831\n   19  libsystem_pthread.dylib             0x00007ff8173931d3 _pthread_start + 125\n   20  libsystem_pthread.dylib             0x00007ff81738ebd3 thread_start + 15\n       assert False\n", "test_name": "test_3_SearchWBP", "rerun": "0"}, "5": {"status": "FAIL", "message": "           ConnectionRefusedError: [Errno 61] Connection refused\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x154593850>: Failed to establish a new connection: [Errno 61] Connection refused\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=49996): Max retries exceeded with url: /session/6aaaaba6a25329b13f64db2647b90254/timeouts (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x154593850>: Failed to establish a new connection: [Errno 61] Connection refused'))\n", "test_name": "test_4_PilihJenisGangguan", "rerun": "0"}}, "suite_name": "4LaporanBulanan/10.Laporan7D/Fungsional/test_Laporan7D.py"}}}, "date": "April 14, 2023", "start_time": 1681405883.106381, "total_suite": 1, "status": "FAIL", "status_list": {"pass": "3", "fail": "3", "skip": "0", "error": "0", "xpass": "0", "xfail": "0", "rerun": "0"}, "total_tests": "6"}