{"content": {"suites": {"0": {"status": {"total_pass": 7, "total_skip": 0, "total_xpass": 0, "total_xfail": 0, "total_rerun": 0, "total_fail": 2, "total_error": 0}, "tests": {"0": {"status": "PASS", "message": "", "test_name": "test_1_SetupOs", "rerun": "0"}, "1": {"status": "PASS", "message": "", "test_name": "test_2_Login", "rerun": "0"}, "2": {"status": "PASS", "message": "", "test_name": "test_2_AksesMenu", "rerun": "0"}, "3": {"status": "PASS", "message": "", "test_name": "test_3_CreateButton", "rerun": "0"}, "4": {"status": "PASS", "message": "", "test_name": "test_3_SearchWBP", "rerun": "0"}, "5": {"status": "PASS", "message": "", "test_name": "test_4_PilihJenisGangguan", "rerun": "0"}, "6": {"status": "PASS", "message": "", "test_name": "test_5_ClickButtonDaftarkan", "rerun": "0"}, "7": {"status": "FAIL", "message": "       assert False\n", "test_name": "test_6_PilihJenisGangguan", "rerun": "0"}, "8": {"status": "FAIL", "message": "           ConnectionRefusedError: [Errno 61] Connection refused\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x114477280>: Failed to establish a new connection: [Errno 61] Connection refused\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=50885): Max retries exceeded with url: /session/e24f2429b1781d7d88bb687e9446574c/window (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x114477280>: Failed to establish a new connection: [Errno 61] Connection refused'))\n", "test_name": "test_29_exit", "rerun": "0"}}, "suite_name": "4LaporanBulanan/10.Laporan7D/Fungsional/test_Laporan7D.py"}}}, "date": "April 13, 2023", "start_time": 1681363506.541054, "total_suite": 1, "status": "FAIL", "status_list": {"pass": "7", "fail": "2", "skip": "0", "error": "0", "xpass": "0", "xfail": "0", "rerun": "0"}, "total_tests": "9"}