{"content": {"suites": {"0": {"status": {"total_pass": 15, "total_skip": 0, "total_xpass": 0, "total_xfail": 0, "total_rerun": 0, "total_fail": 2, "total_error": 0}, "tests": {"0": {"status": "PASS", "message": "", "test_name": "test_1_SetupOs", "rerun": "0"}, "1": {"status": "PASS", "message": "", "test_name": "test_2_Login", "rerun": "0"}, "2": {"status": "PASS", "message": "", "test_name": "test_3_AksesMenu", "rerun": "0"}, "3": {"status": "PASS", "message": "", "test_name": "test_4_ClickButtonTambah", "rerun": "0"}, "4": {"status": "PASS", "message": "", "test_name": "test_5_penanggungJawab", "rerun": "0"}, "5": {"status": "PASS", "message": "", "test_name": "test_6_jumlahAnggota", "rerun": "0"}, "6": {"status": "PASS", "message": "", "test_name": "test_7_pembagianTugas", "rerun": "0"}, "7": {"status": "PASS", "message": "", "test_name": "test_11_keterangan", "rerun": "0"}, "8": {"status": "PASS", "message": "", "test_name": "test_9_permasalahan", "rerun": "0"}, "9": {"status": "PASS", "message": "", "test_name": "test_8_rekapitulasiKehadiran", "rerun": "0"}, "10": {"status": "PASS", "message": "", "test_name": "test_10_alternatifPenyelesaian", "rerun": "0"}, "11": {"status": "PASS", "message": "", "test_name": "test_12_simpan", "rerun": "0"}, "12": {"status": "PASS", "message": "", "test_name": "test_13_SetupOs", "rerun": "0"}, "13": {"status": "PASS", "message": "", "test_name": "test_14_LoginSPV", "rerun": "0"}, "14": {"status": "PASS", "message": "", "test_name": "test_15_AksesMenuSpv", "rerun": "0"}, "15": {"status": "FAIL", "message": "   selenium.common.exceptions.TimeoutException: Message:\n       assert False\n", "test_name": "test_16_KirimLaporanSpv", "rerun": "0"}, "16": {"status": "FAIL", "message": "           ConnectionRefusedError: [Errno 61] Connection refused\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x1220082e0>: Failed to establish a new connection: [Errno 61] Connection refused\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=50462): Max retries exceeded with url: /session/e7c047179852dd142c2ff42ec6a096f4/window (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1220082e0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n", "test_name": "test_31_exit", "rerun": "0"}}, "suite_name": "4LaporanBulanan/12.Laporan8B/Fungsional/test_laporan8B.py"}}}, "date": "May 02, 2023", "start_time": 1682992179.459877, "total_suite": 1, "status": "FAIL", "status_list": {"pass": "15", "fail": "2", "skip": "0", "error": "0", "xpass": "0", "xfail": "0", "rerun": "0"}, "total_tests": "17"}