{"content": {"suites": {"0": {"status": {"total_pass": 9, "total_skip": 0, "total_xpass": 0, "total_xfail": 0, "total_rerun": 0, "total_fail": 3, "total_error": 0}, "tests": {"0": {"status": "PASS", "message": "", "test_name": "test_1_SetupOs", "rerun": "0"}, "1": {"status": "PASS", "message": "", "test_name": "test_2_Login", "rerun": "0"}, "2": {"status": "PASS", "message": "", "test_name": "test_3_AksesMenu", "rerun": "0"}, "3": {"status": "PASS", "message": "", "test_name": "test_4_ClickButtonTambah", "rerun": "0"}, "4": {"status": "PASS", "message": "", "test_name": "test_5_penanggungJawab", "rerun": "0"}, "5": {"status": "PASS", "message": "", "test_name": "test_6_jumlahAnggota", "rerun": "0"}, "6": {"status": "PASS", "message": "", "test_name": "test_7_pembagianTugas", "rerun": "0"}, "7": {"status": "PASS", "message": "", "test_name": "test_8_rekapitulasiKehadiran", "rerun": "0"}, "8": {"status": "PASS", "message": "", "test_name": "test_9_permasalahan", "rerun": "0"}, "9": {"status": "FAIL", "message": "   selenium.common.exceptions.TimeoutException: Message: \n   Stacktrace:\n   0   chromedriver                        0x000000010459cae8 chromedriver + 4958952\n   1   chromedriver                        0x00000001045947b3 chromedriver + 4925363\n   2   chromedriver                        0x00000001041561d6 chromedriver + 475606\n   3   chromedriver                        0x0000000104199a20 chromedriver + 752160\n   4   chromedriver                        0x0000000104199c81 chromedriver + 752769\n   5   chromedriver                        0x00000001041ddf64 chromedriver + 1032036\n   6   chromedriver                        0x00000001041bfc3d chromedriver + 908349\n   7   chromedriver                        0x00000001041db25b chromedriver + 1020507\n   8   chromedriver                        0x00000001041bf9e3 chromedriver + 907747\n   9   chromedriver                        0x0000000104189aef chromedriver + 686831\n   10  chromedriver                        0x000000010418b00e chromedriver + 692238\n   11  chromedriver                        0x00000001045589ad chromedriver + 4680109\n   12  chromedriver                        0x000000010455dc12 chromedriver + 4701202\n   13  chromedriver                        0x000000010456479f chromedriver + 4728735\n   14  chromedriver                        0x000000010455eb7a chromedriver + 4705146\n   15  chromedriver                        0x000000010453127e chromedriver + 4518526\n   16  chromedriver                        0x000000010457e908 chromedriver + 4835592\n   17  chromedriver                        0x000000010457ea87 chromedriver + 4835975\n   18  chromedriver                        0x000000010458e00f chromedriver + 4898831\n   19  libsystem_pthread.dylib             0x00007ff803d171d3 _pthread_start + 125\n   20  libsystem_pthread.dylib             0x00007ff803d12bd3 thread_start + 15\n       assert False\n", "test_name": "test_10_alternatifPenyelesaian", "rerun": "0"}, "10": {"status": "FAIL", "message": "           ConnectionRefusedError: [Errno 61] Connection refused\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x121d1ee80>: Failed to establish a new connection: [Errno 61] Connection refused\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=59743): Max retries exceeded with url: /session/8cdd3aeddb0bb67cf3153fcad0e2198d/timeouts (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x121d1ee80>: Failed to establish a new connection: [Errno 61] Connection refused'))\n", "test_name": "test_11_keterangan", "rerun": "0"}, "11": {"status": "FAIL", "message": "           ConnectionRefusedError: [Errno 61] Connection refused\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x1275fe070>: Failed to establish a new connection: [Errno 61] Connection refused\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=59743): Max retries exceeded with url: /session/8cdd3aeddb0bb67cf3153fcad0e2198d/window (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1275fe070>: Failed to establish a new connection: [Errno 61] Connection refused'))\n", "test_name": "test_32_exit", "rerun": "0"}}, "suite_name": "4LaporanBulanan/12.Laporan8B/Fungsional/test_laporan8B.py"}}}, "date": "April 26, 2023", "start_time": 1682494147.0683079, "total_suite": 1, "status": "FAIL", "status_list": {"pass": "9", "fail": "3", "skip": "0", "error": "0", "xpass": "0", "xfail": "0", "rerun": "0"}, "total_tests": "12"}