{"content": {"suites": {"0": {"status": {"total_pass": 5, "total_skip": 0, "total_xpass": 0, "total_xfail": 0, "total_rerun": 0, "total_fail": 4, "total_error": 0}, "tests": {"0": {"status": "PASS", "message": "", "test_name": "test_17_loginKanwil", "rerun": "0"}, "1": {"status": "PASS", "message": "", "test_name": "test_18_AksesMenuKanwil", "rerun": "0"}, "2": {"status": "PASS", "message": "", "test_name": "test_19_VerifikasiLaporanKanwil", "rerun": "0"}, "3": {"status": "PASS", "message": "", "test_name": "test_20_ClickButtonSearch", "rerun": "0"}, "4": {"status": "PASS", "message": "", "test_name": "test_21_ClickButtonVerifikasi", "rerun": "0"}, "5": {"status": "FAIL", "message": "   selenium.common.exceptions.TimeoutException: Message:\n       assert False\n", "test_name": "test_22_StatusVerifikasiModal", "rerun": "0"}, "6": {"status": "FAIL", "message": "           ConnectionRefusedError: [Errno 61] Connection refused\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x12cd554c0>: Failed to establish a new connection: [Errno 61] Connection refused\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=52438): Max retries exceeded with url: /session/727e4a9da0ef25a79514173a7ce648ab/timeouts (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x12cd554c0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n", "test_name": "test_23_UbahStatus", "rerun": "0"}, "7": {"status": "FAIL", "message": "           ConnectionRefusedError: [Errno 61] Connection refused\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x12ea58e80>: Failed to establish a new connection: [Errno 61] Connection refused\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=52438): Max retries exceeded with url: /session/727e4a9da0ef25a79514173a7ce648ab/timeouts (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x12ea58e80>: Failed to establish a new connection: [Errno 61] Connection refused'))\n", "test_name": "test_24_Inputketerangan", "rerun": "0"}, "8": {"status": "FAIL", "message": "           ConnectionRefusedError: [Errno 61] Connection refused\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x12eb493d0>: Failed to establish a new connection: [Errno 61] Connection refused\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=52438): Max retries exceeded with url: /session/727e4a9da0ef25a79514173a7ce648ab/timeouts (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x12eb493d0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n", "test_name": "test_25_SimpanVerifikasi", "rerun": "0"}}, "suite_name": "4LaporanBulanan/12.Laporan8B/Fungsional/test_laporan8B.py"}}}, "date": "May 02, 2023", "start_time": 1682993406.5950289, "total_suite": 1, "status": "FAIL", "status_list": {"pass": "5", "fail": "4", "skip": "0", "error": "0", "xpass": "0", "xfail": "0", "rerun": "0"}, "total_tests": "9"}