{"content": {"suites": {"0": {"status": {"total_pass": 4, "total_skip": 0, "total_xpass": 0, "total_xfail": 0, "total_rerun": 0, "total_fail": 1, "total_error": 0}, "tests": {"0": {"status": "PASS", "message": "", "test_name": "test_13_SetupOs", "rerun": "0"}, "1": {"status": "PASS", "message": "", "test_name": "test_14_LoginSPV", "rerun": "0"}, "2": {"status": "PASS", "message": "", "test_name": "test_15_AksesMenuSpv", "rerun": "0"}, "3": {"status": "PASS", "message": "", "test_name": "test_16_KirimLaporanSpv", "rerun": "0"}, "4": {"status": "FAIL", "message": "           ConnectionRefusedError: [Errno 61] Connection refused\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x12e765be0>: Failed to establish a new connection: [Errno 61] Connection refused\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=50609): Max retries exceeded with url: /session/6a57262cf763d9e3ecdf0b308b357efe/window (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x12e765be0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n", "test_name": "test_31_exit", "rerun": "0"}}, "suite_name": "4LaporanBulanan/12.Laporan8B/Fungsional/test_laporan8B.py"}}}, "date": "May 02, 2023", "start_time": 1682992278.532613, "total_suite": 1, "status": "FAIL", "status_list": {"pass": "4", "fail": "1", "skip": "0", "error": "0", "xpass": "0", "xfail": "0", "rerun": "0"}, "total_tests": "5"}